//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CY.IoTM.SystemInterface.UM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UM.UserManageWebServiceSoap")]
    public interface UserManageWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddIotUser", ReplyAction="*")]
        CY.IoTM.SystemInterface.UM.AddIotUserResponse AddIotUser(CY.IoTM.SystemInterface.UM.AddIotUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateIotUser", ReplyAction="*")]
        CY.IoTM.SystemInterface.UM.UpdateIotUserResponse UpdateIotUser(CY.IoTM.SystemInterface.UM.UpdateIotUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadIotUser", ReplyAction="*")]
        CY.IoTM.SystemInterface.UM.ReadIotUserResponse ReadIotUser(CY.IoTM.SystemInterface.UM.ReadIotUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddIotUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddIotUser", Namespace="http://tempuri.org/", Order=0)]
        public CY.IoTM.SystemInterface.UM.AddIotUserRequestBody Body;
        
        public AddIotUserRequest() {
        }
        
        public AddIotUserRequest(CY.IoTM.SystemInterface.UM.AddIotUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddIotUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userInfoJson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string meterInfoJson;
        
        public AddIotUserRequestBody() {
        }
        
        public AddIotUserRequestBody(string account, string pwd, string userInfoJson, string meterInfoJson) {
            this.account = account;
            this.pwd = pwd;
            this.userInfoJson = userInfoJson;
            this.meterInfoJson = meterInfoJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddIotUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddIotUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CY.IoTM.SystemInterface.UM.AddIotUserResponseBody Body;
        
        public AddIotUserResponse() {
        }
        
        public AddIotUserResponse(CY.IoTM.SystemInterface.UM.AddIotUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddIotUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddIotUserResult;
        
        public AddIotUserResponseBody() {
        }
        
        public AddIotUserResponseBody(string AddIotUserResult) {
            this.AddIotUserResult = AddIotUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateIotUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateIotUser", Namespace="http://tempuri.org/", Order=0)]
        public CY.IoTM.SystemInterface.UM.UpdateIotUserRequestBody Body;
        
        public UpdateIotUserRequest() {
        }
        
        public UpdateIotUserRequest(CY.IoTM.SystemInterface.UM.UpdateIotUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateIotUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userInfoJson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string meterInfoJson;
        
        public UpdateIotUserRequestBody() {
        }
        
        public UpdateIotUserRequestBody(string account, string pwd, string userInfoJson, string meterInfoJson) {
            this.account = account;
            this.pwd = pwd;
            this.userInfoJson = userInfoJson;
            this.meterInfoJson = meterInfoJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateIotUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateIotUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CY.IoTM.SystemInterface.UM.UpdateIotUserResponseBody Body;
        
        public UpdateIotUserResponse() {
        }
        
        public UpdateIotUserResponse(CY.IoTM.SystemInterface.UM.UpdateIotUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateIotUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateIotUserResult;
        
        public UpdateIotUserResponseBody() {
        }
        
        public UpdateIotUserResponseBody(string UpdateIotUserResult) {
            this.UpdateIotUserResult = UpdateIotUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadIotUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadIotUser", Namespace="http://tempuri.org/", Order=0)]
        public CY.IoTM.SystemInterface.UM.ReadIotUserRequestBody Body;
        
        public ReadIotUserRequest() {
        }
        
        public ReadIotUserRequest(CY.IoTM.SystemInterface.UM.ReadIotUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadIotUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int count;
        
        public ReadIotUserRequestBody() {
        }
        
        public ReadIotUserRequestBody(string account, string pwd, int index, int count) {
            this.account = account;
            this.pwd = pwd;
            this.index = index;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadIotUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadIotUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CY.IoTM.SystemInterface.UM.ReadIotUserResponseBody Body;
        
        public ReadIotUserResponse() {
        }
        
        public ReadIotUserResponse(CY.IoTM.SystemInterface.UM.ReadIotUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadIotUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadIotUserResult;
        
        public ReadIotUserResponseBody() {
        }
        
        public ReadIotUserResponseBody(string ReadIotUserResult) {
            this.ReadIotUserResult = ReadIotUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserManageWebServiceSoapChannel : CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManageWebServiceSoapClient : System.ServiceModel.ClientBase<CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap>, CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap {
        
        public UserManageWebServiceSoapClient() {
        }
        
        public UserManageWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManageWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManageWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManageWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CY.IoTM.SystemInterface.UM.AddIotUserResponse CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap.AddIotUser(CY.IoTM.SystemInterface.UM.AddIotUserRequest request) {
            return base.Channel.AddIotUser(request);
        }
        
        public string AddIotUser(string account, string pwd, string userInfoJson, string meterInfoJson) {
            CY.IoTM.SystemInterface.UM.AddIotUserRequest inValue = new CY.IoTM.SystemInterface.UM.AddIotUserRequest();
            inValue.Body = new CY.IoTM.SystemInterface.UM.AddIotUserRequestBody();
            inValue.Body.account = account;
            inValue.Body.pwd = pwd;
            inValue.Body.userInfoJson = userInfoJson;
            inValue.Body.meterInfoJson = meterInfoJson;
            CY.IoTM.SystemInterface.UM.AddIotUserResponse retVal = ((CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap)(this)).AddIotUser(inValue);
            return retVal.Body.AddIotUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CY.IoTM.SystemInterface.UM.UpdateIotUserResponse CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap.UpdateIotUser(CY.IoTM.SystemInterface.UM.UpdateIotUserRequest request) {
            return base.Channel.UpdateIotUser(request);
        }
        
        public string UpdateIotUser(string account, string pwd, string userInfoJson, string meterInfoJson) {
            CY.IoTM.SystemInterface.UM.UpdateIotUserRequest inValue = new CY.IoTM.SystemInterface.UM.UpdateIotUserRequest();
            inValue.Body = new CY.IoTM.SystemInterface.UM.UpdateIotUserRequestBody();
            inValue.Body.account = account;
            inValue.Body.pwd = pwd;
            inValue.Body.userInfoJson = userInfoJson;
            inValue.Body.meterInfoJson = meterInfoJson;
            CY.IoTM.SystemInterface.UM.UpdateIotUserResponse retVal = ((CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap)(this)).UpdateIotUser(inValue);
            return retVal.Body.UpdateIotUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CY.IoTM.SystemInterface.UM.ReadIotUserResponse CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap.ReadIotUser(CY.IoTM.SystemInterface.UM.ReadIotUserRequest request) {
            return base.Channel.ReadIotUser(request);
        }
        
        public string ReadIotUser(string account, string pwd, int index, int count) {
            CY.IoTM.SystemInterface.UM.ReadIotUserRequest inValue = new CY.IoTM.SystemInterface.UM.ReadIotUserRequest();
            inValue.Body = new CY.IoTM.SystemInterface.UM.ReadIotUserRequestBody();
            inValue.Body.account = account;
            inValue.Body.pwd = pwd;
            inValue.Body.index = index;
            inValue.Body.count = count;
            CY.IoTM.SystemInterface.UM.ReadIotUserResponse retVal = ((CY.IoTM.SystemInterface.UM.UserManageWebServiceSoap)(this)).ReadIotUser(inValue);
            return retVal.Body.ReadIotUserResult;
        }
    }
}
