--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期二, 14 七月, 2015 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期二, 14 七月, 2015 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

CREATE TABLE IoT_ValveControl ( 
	ID bigint identity(1,1)  NOT NULL,    -- 索引 
	UserID char(10),    -- 用户ID 
	MeterID bigint,    -- 表索引号 
	MeterNo varchar(20),    -- 表号 
	RegisterDate datetime,    -- 阀门控制申请日期 
	Reason varchar(500),    -- 申请原因 
	ControlType char(1),    -- 控制类型：0 关阀 1 开发 
	State char(1),    -- 状态：0 申请 1 撤销 2 完成 3 失败 
	FinishedDate datetime,    -- 任务完成时间 
	Oper varchar(50),    -- 操作员 
	Context varchar(50),    -- 备注（主要说明控制失败原因） 
	CompanyID char(4),    -- 企业代码 
	TaskID varchar(50) NOT NULL    -- 本次任务ID，由通讯层注册本次任务后提供。 
)
;
GO
EXEC sp_addextendedproperty 'MS_Description', '燃气表阀门控制（开、关阀）操作记录表', 'Schema', dbo, 'table', IoT_ValveControl
;
GO
EXEC sp_addextendedproperty 'MS_Description', '索引', 'Schema', dbo, 'table', IoT_ValveControl, 'column', ID
;
GO
EXEC sp_addextendedproperty 'MS_Description', '用户ID', 'Schema', dbo, 'table', IoT_ValveControl, 'column', UserID
;
GO
EXEC sp_addextendedproperty 'MS_Description', '表索引号', 'Schema', dbo, 'table', IoT_ValveControl, 'column', MeterID
;
GO
EXEC sp_addextendedproperty 'MS_Description', '表号', 'Schema', dbo, 'table', IoT_ValveControl, 'column', MeterNo
;
GO
EXEC sp_addextendedproperty 'MS_Description', '阀门控制申请日期', 'Schema', dbo, 'table', IoT_ValveControl, 'column', RegisterDate
;
GO
EXEC sp_addextendedproperty 'MS_Description', '申请原因', 'Schema', dbo, 'table', IoT_ValveControl, 'column', Reason
;
GO
EXEC sp_addextendedproperty 'MS_Description', '控制类型：0 关阀 1 开发', 'Schema', dbo, 'table', IoT_ValveControl, 'column', ControlType
;
GO
EXEC sp_addextendedproperty 'MS_Description', '状态：0 申请 1 撤销 2 完成 3 失败', 'Schema', dbo, 'table', IoT_ValveControl, 'column', State
;
GO
EXEC sp_addextendedproperty 'MS_Description', '任务完成时间', 'Schema', dbo, 'table', IoT_ValveControl, 'column', FinishedDate
;
GO
EXEC sp_addextendedproperty 'MS_Description', '操作员', 'Schema', dbo, 'table', IoT_ValveControl, 'column', Oper
;
GO
EXEC sp_addextendedproperty 'MS_Description', '备注（主要说明控制失败原因）', 'Schema', dbo, 'table', IoT_ValveControl, 'column', Context
;
GO
EXEC sp_addextendedproperty 'MS_Description', '企业代码', 'Schema', dbo, 'table', IoT_ValveControl, 'column', CompanyID
;
GO
EXEC sp_addextendedproperty 'MS_Description', '本次任务ID，由通讯层注册本次任务后提供。', 'Schema', dbo, 'table', IoT_ValveControl, 'column', TaskID
;
GO
ALTER TABLE IoT_ValveControl ADD CONSTRAINT PK_IoT_ValveControl 
	PRIMARY KEY CLUSTERED (TaskID)
;