--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期二, 21 七月, 2015 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

CREATE TABLE IoT_DayReadMeter ( 
	ID bigint identity(1,1)  NOT NULL,    -- 索引号 
	MeterID bigint,    -- 对应燃气表索引号 
	MeterNo char(20),    -- 对应表号 
	Ser int,    -- 燃气表上报序号 
	Gas decimal(10,2),    -- 本次抄表总用量 
	ReadDate datetime,    -- 本次抄表时间 
	RemainingAmount money,    -- 剩余金额（仅对金额表） 
	LastTotal decimal(10,2),    -- 上期结算时总用量 
	ST1 char(16),    -- 字符顺序：X X X 0 0  X X X X   X  X   X   X   X  X   X                      1 2  3 4  5 6 7  8 9  10 11 12 13 14 15 16  第1-2 字符表示阀门状态，00：开；01：关；10：保留；11：异常 第3个字符表示电池电压，0：正常；1：欠压 第4-5个字符保留，填00 第6个字符表示电源状态，0：正常；1：异常 第7个字符表示外电源状态0：正常；1：异常 第8个字符锂电池状态0：正常；1：异常 第9个字符表类型0：气量表；1：金额表 第10个字符无外电（无外电和内电池）0：未报警  1：报警 第11个字符表示欠压（干电池） 第12个字符表示操作错误/磁干扰 第13个字符表示余额不足/气量用尽 第14个字符表示系统控制关阀 第15个字符燃气表内部错误关阀，请立即与燃气公司联系。（燃气表内部错误，如内电池电量低、内存损坏等） 第16个字符表示长期未与服务器通讯报警 
	ST2 char(8)      -- 字符顺序：X  X  X   X  X   X  X   X                      1   2  3   4   5   6   7  8  字符8         燃气漏气切断报警                0：未报警   1：报警 字符7         流量过载切断报警                0：未报警   1：报警 字符6         异常大流量切断报警            0：未报警   1：报警 字符5         异常微小流量切断报警        0：未报警   1：报警 字符4         持续流量超时切断报警        0：未报警   1：报警 字符3         燃气压力过低切断报警        0：未报警   1：报警 字符2         长期未使用切断报警            0：未报警   1：报警 字符1         移动报警/地震震感器动作切断报警  0：未报警   1：报警 
)
;


GO
EXEC sp_addextendedproperty 'MS_Description', '字符顺序：X  X  X   X  X   X  X   X 
                    1   2  3   4   5   6   7  8 
字符8         燃气漏气切断报警                0：未报警   1：报警
字符7         流量过载切断报警                0：未报警   1：报警
字符6         异常大流量切断报警            0：未报警   1：报警
字符5         异常微小流量切断报警        0：未报警   1：报警
字符4         持续流量超时切断报警        0：未报警   1：报警
字符3         燃气压力过低切断报警        0：未报警   1：报警
字符2         长期未使用切断报警            0：未报警   1：报警
字符1         移动报警/地震震感器动作切断报警  0：未报警   1：报警', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', ST2
;


GO
EXEC sp_addextendedproperty 'MS_Description', '字符顺序：X X X 0 0  X X X X   X  X   X   X   X  X   X 
                    1 2  3 4  5 6 7  8 9  10 11 12 13 14 15 16 
第1-2 字符表示阀门状态，00：开；01：关；10：保留；11：异常
第3个字符表示电池电压，0：正常；1：欠压
第4-5个字符保留，填00
第6个字符表示电源状态，0：正常；1：异常
第7个字符表示外电源状态0：正常；1：异常
第8个字符锂电池状态0：正常；1：异常
第9个字符表类型0：气量表；1：金额表
第10个字符无外电（无外电和内电池）0：未报警  1：报警
第11个字符表示欠压（干电池）
第12个字符表示操作错误/磁干扰
第13个字符表示余额不足/气量用尽
第14个字符表示系统控制关阀
第15个字符燃气表内部错误关阀，请立即与燃气公司联系。（燃气表内部错误，如内电池电量低、内存损坏等）
第16个字符表示长期未与服务器通讯报警', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', ST1
;


GO
EXEC sp_addextendedproperty 'MS_Description', '上期结算时总用量', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', LastTotal
;


GO
EXEC sp_addextendedproperty 'MS_Description', '剩余金额（仅对金额表）', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', RemainingAmount
;


GO
EXEC sp_addextendedproperty 'MS_Description', '本次抄表时间', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', ReadDate
;


GO
EXEC sp_addextendedproperty 'MS_Description', '本次抄表总用量', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', Gas
;


GO
EXEC sp_addextendedproperty 'MS_Description', '燃气表上报序号', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', Ser
;


GO
EXEC sp_addextendedproperty 'MS_Description', '对应表号', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', MeterNo
;


GO
EXEC sp_addextendedproperty 'MS_Description', '对应燃气表索引号', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', MeterID
;


GO
EXEC sp_addextendedproperty 'MS_Description', '索引号', 'Schema', dbo, 'table', IoT_DayReadMeter, 'column', ID
;


GO
EXEC sp_addextendedproperty 'MS_Description', '抄表数据，每天接收到的第一条记录
注：该表中每天最多存储一条记录。', 'Schema', dbo, 'table', IoT_DayReadMeter
;


GO
ALTER TABLE IoT_DayReadMeter ADD CONSTRAINT PK_IoT_DayReadMeter 
	PRIMARY KEY CLUSTERED (ID)
;
GO
ALTER TABLE [dbo].[IoT_DayReadMeter] ADD  DEFAULT 00000000 FOR [ST2]
;