--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期四, 16 七月, 2015 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

CREATE TABLE IoT_MeterDataHistory ( 
	ID bigint identity(1,1)  NOT NULL,    -- 索引 
	MeterID bigint,    -- 燃气表索引号 
	MeterNo varchar(20),
	Ser int,    -- 上传序号 
	Gas decimal(10,2),    -- 表累计用气量 
	ReadDate datetime,    -- 抄表时间 
	RemainingAmount money,    -- 当前剩余金额 
	LastTotal decimal(10,2),
	ST1 char(16),
	ST2 char(8)
)
;
GO
ALTER TABLE IoT_MeterDataHistory ADD CONSTRAINT PK_IoT_MeterDataHistory 
	PRIMARY KEY CLUSTERED (ID)
;
GO
EXEC sp_addextendedproperty 'MS_Description', '抄表数据历史，记录燃气表发回的每一条用气数据', 'Schema', dbo, 'table', IoT_MeterDataHistory
;
GO
EXEC sp_addextendedproperty 'MS_Description', '索引', 'Schema', dbo, 'table', IoT_MeterDataHistory, 'column', ID
;
GO
EXEC sp_addextendedproperty 'MS_Description', '燃气表索引号', 'Schema', dbo, 'table', IoT_MeterDataHistory, 'column', MeterID
;
GO
EXEC sp_addextendedproperty 'MS_Description', '上传序号', 'Schema', dbo, 'table', IoT_MeterDataHistory, 'column', Ser
;
GO
EXEC sp_addextendedproperty 'MS_Description', '表累计用气量', 'Schema', dbo, 'table', IoT_MeterDataHistory, 'column', Gas
;
GO
EXEC sp_addextendedproperty 'MS_Description', '抄表时间', 'Schema', dbo, 'table', IoT_MeterDataHistory, 'column', ReadDate
;
GO
EXEC sp_addextendedproperty 'MS_Description', '当前剩余金额', 'Schema', dbo, 'table', IoT_MeterDataHistory, 'column', RemainingAmount
;