--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.5.845
--   Created On : 星期二, 14 八月, 2012 
--   DBMS       : SQL Server 2005 
--   -------------------------------------------------- 




--  Create Tables 
CREATE TABLE ReportDataParameter ( 
	RD_ID int NOT NULL,    --  报表模板ID 
	ParameterName varchar(50) NOT NULL,    --  参数名称 
	ParameterType smallint,    --  参数类型 
	ParameterLength int,    --  参数长度 
	ParameterValue varchar(500),    --  参数默认值 
	OrderID smallint DEFAULT ((0)),    --  参数加载序号 
	bz varchar(500),    --  备注 
	ParType smallint DEFAULT ((0)),
	DisplayMember varchar(50),
	ValueMember varchar(50),
	ConnectionString varchar(500),
	CommandType smallint,
	CommandText varchar(2000),
	Script varchar(2000),
	Items varchar(1000)
)


GO
EXEC sp_addextendedproperty 'MS_Description', '报表查询参数表', 'Schema', dbo, 'table', ReportDataParameter
GO
EXEC sp_addextendedproperty 'MS_Description', '报表模板ID', 'Schema', dbo, 'table', ReportDataParameter, 'column', RD_ID
GO
EXEC sp_addextendedproperty 'MS_Description', '参数名称', 'Schema', dbo, 'table', ReportDataParameter, 'column', ParameterName
GO
EXEC sp_addextendedproperty 'MS_Description', '参数类型', 'Schema', dbo, 'table', ReportDataParameter, 'column', ParameterType
GO
EXEC sp_addextendedproperty 'MS_Description', '参数长度', 'Schema', dbo, 'table', ReportDataParameter, 'column', ParameterLength
GO
EXEC sp_addextendedproperty 'MS_Description', '参数默认值', 'Schema', dbo, 'table', ReportDataParameter, 'column', ParameterValue
GO
EXEC sp_addextendedproperty 'MS_Description', '参数加载序号', 'Schema', dbo, 'table', ReportDataParameter, 'column', OrderID
GO
EXEC sp_addextendedproperty 'MS_Description', '备注', 'Schema', dbo, 'table', ReportDataParameter, 'column', bz

