--创源管理帐号

delete from S_CompanyInfo
DELETE FROM S_CompanyOperator

INSERT INTO S_CompanyInfo
                      (CompanyID, CompanyName, SimpleName, Provinces, City, Status)
VALUES     ('zzcy', '郑州创源', '郑州创源', '河南', '郑州', 0)


INSERT INTO S_CompanyOperator
                      (OperID, CompanyID, Pwd, Name, State, OperType)
VALUES     ('zzcy', 'zzcy', '94792920b8b3b24c9c59c4a5f6d59c', '总管理员', '0', 1)

--默认权限组
DELETE FROM S_DefineRight
DELETE FROM S_DefineOperRight
INSERT INTO S_DefineRight (RightCode, CompanyID, RightName) VALUES ('xtgly', 'zzcy', '系统控制权限')
INSERT INTO S_DefineOperRight( CompanyID, OperID, RightCode) values ('zzcy','zzcy','xtgly')


--创源管理帐号权限菜单

delete from S_CompanyMenu

insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bbgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjaz_azbj')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjcd')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjczy')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjgl_szcs')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjgl_xxcx')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjqxz')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','bjzcqy')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','cdgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','chaobiao')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','chaobiaoM')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','CHONGZHI')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','ChongZhiM')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','chongZhiQ')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','cjfwqlb')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','cjyh_dhcj')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','CZ_CXCZ')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','czmm')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','czygl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','dagl_bjyh')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','dagl_scyh')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','dcbbmb')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','DENGJI')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','dhtq_cx')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','dhtq_dh')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','drbbmb')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','duilie')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fbgg')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','ggpUser')-----New
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','ggPublish')-----New
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','ggzt')-----New
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fbls')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fmcz_cx')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fmcz_gf')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fmcz_kf')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fmkz')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fmkz_czls')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fmkz_fmcz')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fpqxz')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fpqycd')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','fwqcsgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','ggwjgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','gxbbmb')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','huanbiaoM')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','huanbiaoQ')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jgcsgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jggl_bjjg')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jggl_scjg')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jggl_tjjg')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','JieSuanRi')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jqcsgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jqgl_bjjd')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jqgl_bjxq')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jqgl_scjd')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jqgl_scxq')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jqgl_tjjd')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jqgl_tjxq')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','jsxx')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','qcqyqxhc')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','qxzgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','qybbcx')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','qygl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','qyzcgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','qyzzhcsh')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','rqyhgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','RVJSR')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','scbbmb')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','sccd')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','scczy')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','scqxz')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','SCZQREV')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','SetUpLoad')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','SQREVOKE')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','szbjcs')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','szfwqcs')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','tjcd')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','tjczy')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','tjgl_tj')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','tjjh')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','tjjhgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','tjqxz')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','tjzcqy')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','xgbbmc')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','xgmm')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','xtgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','xtrzgl')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','yhgl_bjaz')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','yhgl_cjyh')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','yhgl_dawh')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','yhgl_dhtq')
insert into  S_CompanyMenu (CompanyID, MenuCode ) values ('zzcy','YingYeTin')

--SELECT 'insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values (''' +CompanyID +''','''+ RightCode +''','''+ rtrim(MenuCode) +''')'
--FROM         S_DefineRightMenu

DELETE FROM S_DefineRightMenu
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bbgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjaz_azbj')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjcd')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjczy')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjgl_szcs')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjgl_xxcx')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjqxz')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','bjzcqy')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','cdgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','chaobiao')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','chaobiaoM')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','CHONGZHI')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','ChongZhiM')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','chongZhiQ')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','cjfwqlb')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','cjyh_dhcj')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','CZ_CXCZ')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','czmm')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','czygl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','dagl_bjyh')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','dagl_scyh')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','dcbbmb')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','DENGJI')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','dhtq_cx')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','dhtq_dh')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','drbbmb')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','duilie')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fbgg')

insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fbls')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fmcz_cx')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fmcz_gf')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fmcz_kf')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fmkz')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fmkz_czls')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fmkz_fmcz')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fpqxz')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fpqycd')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','fwqcsgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','ggwjgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','gxbbmb')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','huanbiaoM')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','huanbiaoQ')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jgcsgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jggl_bjjg')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jggl_scjg')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jggl_tjjg')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','JieSuanRi')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jqcsgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jqgl_bjjd')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jqgl_bjxq')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jqgl_scjd')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jqgl_scxq')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jqgl_tjjd')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jqgl_tjxq')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','jsxx')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','qcqyqxhc')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','qxzgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','qybbcx')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','qygl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','qyzcgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','qyzzhcsh')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','rqyhgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','RVJSR')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','scbbmb')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','sccd')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','scczy')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','scqxz')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','SCZQREV')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','SetUpLoad')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','SQREVOKE')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','szbjcs')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','szfwqcs')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','tjcd')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','tjczy')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','tjgl_tj')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','tjjh')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','tjjhgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','tjqxz')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','tjzcqy')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','xgbbmc')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','xgmm')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','xtgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','xtrzgl')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','yhgl_bjaz')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','yhgl_cjyh')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','yhgl_dawh')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','yhgl_dhtq')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly     ','YingYeTin')

insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly','ggwjgl')
--insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly','fbgg')
--insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly','fbls')
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly','ggzt')---news
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly','ggpUser')----news
insert into  S_DefineRightMenu (CompanyID, RightCode, MenuCode) values ('zzcy','xtgly','ggPublish')----news

--select 'insert into  S_CompanyMenu (CompanyID, MenuCode ) values (''zzcy'',''' + rtrim(MenuCode) + ''')' from S_DefineMenu 

