delete from S_DefineMenu

INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bbgl      ', N'报表模板管理', N'01', N'../Report/ReportManage.aspx', N'../Images/Menu/shipping.png', 2, N'qygl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjaz_azbj ', N'安装表具', N'02', N'', N'', 0, N'yhgl_bjaz ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjcd      ', N'编辑菜单', N'02', N'', N'', 1, N'cdgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjczy     ', N'编辑操作员', N'02', N'', N'', 1, N'czygl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjqxz     ', N'编辑权限组', N'02', N'', N'', 1, N'qxzgl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjzcqy    ', N'编辑企业', N'02', N'', N'', 1, N'qyzcgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'cdgl      ', N'菜单管理', N'01', N'../MenuManage.aspx', N'../Images/Menu/shipping.png', 1, N'qygl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'cjyh_dhcj ', N'单户创建', N'02', N'', N'', 0, N'yhgl_cjyh ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'czmm      ', N'重置密码', N'02', N'', N'', 3, N'czygl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'czygl     ', N'操作员管理', N'01', N'../CompanyOperatorManage.aspx', N'../Images/Menu/shipping.png', 1, N'xtgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'dagl_bjyh ', N'编辑用户', N'02', N'', N'', 0, N'yhgl_dawh ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'dagl_scyh ', N'删除用户', N'02', N'', N'', 1, N'yhgl_dawh ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'dcbbmb    ', N'导出报表', N'02', N'', N'', 0, N'bbgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'drbbmb    ', N'导入报表', N'02', N'', N'', 0, N'bbgl      ', NULL)

INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fpqxz     ', N'分配权限组', N'02', N'', N'', 4, N'czygl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fpqycd    ', N'分配菜单', N'02', N'', N'', 3, N'qyzcgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fwqcsgl   ', N'服务器参数管理', N'01', N'../IotM/SystemParManage.aspx', N'../Images/Menu/shipping.png', 4, N'xtgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'gxbbmb    ', N'更新报表', N'02', N'', N'', 0, N'bbgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jgcsgl    ', N'价格参数管理', N'01', N'../IotM/PriceParManage.aspx', N'../Images/Menu/shipping.png', 5, N'xtgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jggl_bjjg ', N'编辑价格类型', N'02', N'', N'', 1, N'jgcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jggl_scjg ', N'删除价格类型', N'02', N'', N'', 2, N'jgcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jggl_tjjg ', N'添加价格类型', N'02', N'', N'', 0, N'jgcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jqcsgl    ', N'街区参数管理', N'01', N'../IotM/StreetManage.aspx', N'../Images/Menu/shipping.png', 6, N'xtgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jqgl_bjjd ', N'编辑街道', N'02', N'', N'', 1, N'jqcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jqgl_bjxq ', N'编辑小区', N'02', N'', N'', 4, N'jqcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jqgl_scjd ', N'删除街道', N'02', N'', N'', 2, N'jqcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jqgl_scxq ', N'删除小区', N'02', N'', N'', 5, N'jqcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jqgl_tjjd ', N'添加街道', N'02', N'', N'', 0, N'jqcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jqgl_tjxq ', N'添加小区', N'02', N'', N'', 3, N'jqcsgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'qcqyqxhc  ', N'清除缓存', N'02', N'', N'', 4, N'qyzcgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'qxzgl     ', N'权限组管理', N'01', N'../CompanyRightManage.aspx', N'../Images/Menu/shipping.png', 0, N'xtgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'qybbcx    ', N'企业报表查询', N'01', N'../Report/CompanyReportManage.aspx', N'../Images/Menu/shipping.png', 3, N'qygl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'qygl      ', N'企业管理', N'00', N'', N'', 0, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'qyzcgl    ', N'企业管理', N'01', N'../CompanyManage.aspx', N'../Images/Menu/shipping.png', 0, N'qygl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'qyzzhcsh  ', N'企业主账号初始化', N'02', N'', N'', 2, N'qyzcgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'rqyhgl    ', N'用户管理', N'00', N'', N'', 2, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'scbbmb    ', N'删除报表', N'02', N'', N'', 0, N'bbgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'sccd      ', N'删除菜单', N'02', N'', N'', 2, N'cdgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'scczy     ', N'删除操作员', N'02', N'', N'', 2, N'czygl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'scqxz     ', N'删除权限组', N'02', N'', N'', 2, N'qxzgl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'szfwqcs   ', N'设置服务器参数', N'02', N'', N'', 0, N'fwqcsgl   ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'tjcd      ', N'添加菜单', N'02', N'', N'', 0, N'cdgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'tjczy     ', N'添加操作员', N'02', N'', N'', 0, N'czygl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'tjqxz     ', N'添加权限组', N'02', N'', N'', 0, N'qxzgl     ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'tjzcqy    ', N'添加企业', N'02', N'', N'', 0, N'qyzcgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'xgbbmc    ', N'修改报表名称', N'02', N'', N'', 0, N'bbgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'xgmm      ', N'修改密码', N'01', N'../OperatorChangePwd.aspx', N'../Images/Menu/shipping.png', 3, N'xtgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'xtgl      ', N'系统管理', N'00', N'', N'', 1, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'xtrzgl    ', N'系统日志', N'01', N'../SystemLogManage.aspx', N'../Images/Menu/shipping.png', 2, N'xtgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'yhgl_bjaz ', N'表具安装', N'01', N'../IotM/MeterInstall.aspx', N'../Images/Menu/shipping.png', 2, N'rqyhgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'yhgl_cjyh ', N'创建用户', N'01', N'../IotM/UserCreate.aspx', N'../Images/Menu/shipping.png', 1, N'rqyhgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'yhgl_dawh ', N'档案维护', N'01', N'../IotM/UserManage.aspx', N'../Images/Menu/shipping.png', 0, N'rqyhgl    ', NULL)

INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'yhgl_dhtq ', N'点火通气', N'01', N'../IotM/DianHuoManage.aspx', N'../Images/Menu/shipping.png', 2, N'rqyhgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'dhtq_dh   ', N'点火', N'02', N'', N'', 0, N'yhgl_dhtq   ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'dhtq_cx   ', N'撤销点火',N'02', N'', N'', 0, N'yhgl_dhtq   ', NULL)


INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjgl      ', N'报警管理', N'00', N'', N'', 4, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjgl_szcs ', N'报警参数设置', N'01', N'../IotM/SetAlarmManage.aspx', N'../Images/Menu/shipping.png', 0, N'bjgl      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'szbjcs    ', N'设置报警参数', N'02', N'', N'', 0, N'bjgl_szcs   ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'bjgl_xxcx ', N'报警信息查询', N'01', N'../IotM/AlarmInfoManage.aspx', N'../Images/Menu/shipping.png', 0, N'bjgl      ', NULL)


INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fmcz_cx   ', N'撤销阀门操作', N'02', N'', N'', 0, N'fmkz_czls ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fmcz_gf   ', N'关阀', N'02', N'', N'', 1, N'fmkz_fmcz ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fmcz_kf   ', N'开阀', N'02', N'', N'', 0, N'fmkz_fmcz ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fmkz      ', N'阀门控制', N'00', N'', N'', 3, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fmkz_czls ', N'阀门操作历史', N'01', N'../IotM/ValveControlManage.aspx', N'../Images/Menu/shipping.png', 0, N'fmkz      ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fmkz_fmcz ', N'阀门操作', N'01', N'../IotM/ValveControl.aspx', N'../Images/Menu/shipping.png', 1, N'fmkz      ', NULL)


INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'tjjhgl    ', N'调价管理', N'00', N'', N'', 6, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'tjjh      ', N'调价计划', N'01', N'../IotM/PricingManage.aspx', N'../Images/Menu/shipping.png', 0, N'tjjhgl    ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'tjgl_tj   ', N'设置调价计划', N'02', N'', N'', 0, N'tjjh   ', NULL)


INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'chaobiaoM   ', N'抄表管理', N'00', N' ', N' ', 5, N' ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'chaobiao   ', N'抄表数据', N'01', N'../IotM/ChaoBiaoManage.aspx', N'../Images/Menu/shipping.png', 1, N'chaobiaoM', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'SetUpLoad', N'设置上传周期', N'01', N'../IotM/SetUpLoadDate.aspx', N'../Images/Menu/shipping.png', 2, N'chaobiaoM', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'SCZQREV ', N'撤销上传周期', N'02', N'', N'', 1, N'SetUpLoad ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'qlbjs   ', N'气量表结算', N'01', N'../IotM/MeterGasBillManage.aspx', N'../Images/Menu/shipping.png', 1, N'chaobiaoM', NULL)



INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'ChongZhiM ', N'充值管理', N'00', N' ', N' ', 4, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'chongZhiQ ', N'充值查询', N'01', N'../IotM/ChongZhiManege.aspx', N'../Images/Menu/shipping.png', 1, N'ChongZhiM ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'YingYeTin ', N'营业厅充值', N'01', N'../IotM/YingYeTingCZ.aspx', N'../Images/Menu/shipping.png', 2, N'ChongZhiM ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'duilie    ', N'充值队列查询', N'01', N'../IotM/CZDuiLie.aspx', N'../Images/Menu/shipping.png', 3, N'ChongZhiM ', NULL)
--INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'CZTongJi  ', N'充值统计', N'03', N'../Report/Report.aspx?id=5', N'', 4, N'ChongZhiM ', 5)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'JieSuanRi ', N'设置结算日', N'01', N'../IotM/JieSuanRi.aspx', N'../Images/Menu/shipping.png', 5, N'ChongZhiM ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'CHONGZHI ', N'充值', N'02', N'', N'', 0, N'chongZhiQ ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'CZ_CXCZ ', N'撤销充值', N'02', N'', N'', 1, N'chongZhiQ ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'RVJSR ', N'撤销结算日', N'02', N'', N'', 2, N'JieSuanRi ', NULL)


INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'huanbiaoM ', N'换表管理', N'00', N' ', N' ', 5, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'huanbiaoQ ', N'换表查询', N'01', N'../IotM/HuanBiaoManege.aspx', N'../Images/Menu/shipping.png', 1, N'huanbiaoM ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'SQREVOKE ', N'撤销换表申请', N'02', N'', N'', 1, N'huanbiaoQ ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'DENGJI ', N'换表登记', N'02', N'', N'', 2, N'huanbiaoQ ', NULL)


INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'cjfwqlb ', N'采集服务监控', N'00', N' ', N' ', 8, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'jsxx ', N'监视信息', N'01', N'../IotM/Monitor/MonitorShow.aspx', N'../Images/Menu/shipping.png', 1, N'cjfwqlb ', NULL)


INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'ggwjgl ', N'广告管理', N'00', N' ', N' ', 7, N'          ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'ggzt ', N'广告主题', N'01', N'../AdM/AdContentMain.aspx', N'../Images/Menu/shipping.png', 0, N'ggwjgl ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'ggPublish ', N'广告发布', N'01', N'../AdM/AdPublish.aspx', N'../Images/Menu/shipping.png',1, N'ggwjgl ', NULL)
INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'ggpUser ', N'广告屏用户', N'01', N'../AdM/ADUser.aspx', N'../Images/Menu/shipping.png', 2, N'ggwjgl ', NULL)
--INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fbgg ', N'发布广告', N'01', N'../IotM/AdInfoManage.aspx', N'../Images/Menu/shipping.png', 3, N'ggwjgl ', NULL)
--INSERT [dbo].[S_DefineMenu] ([MenuCode], [Name], [Type], [UrlClass], [ImageUrl], [OrderNum], [FatherCode], [RID]) VALUES (N'fbls ', N'发布历史', N'01', N'../IotM/AdInfoControl.aspx', N'../Images/Menu/shipping.png', 4, N'ggwjgl ', NULL)