#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CY.IoTM.Common.Business
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IotMeter")]
	public partial class AlarmDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertIoT_AlarmInfo(IoT_AlarmInfo instance);
    partial void UpdateIoT_AlarmInfo(IoT_AlarmInfo instance);
    partial void DeleteIoT_AlarmInfo(IoT_AlarmInfo instance);
    partial void InsertIoT_AlarmMeter(IoT_AlarmMeter instance);
    partial void UpdateIoT_AlarmMeter(IoT_AlarmMeter instance);
    partial void DeleteIoT_AlarmMeter(IoT_AlarmMeter instance);
    partial void InsertIoT_SetAlarm(IoT_SetAlarm instance);
    partial void UpdateIoT_SetAlarm(IoT_SetAlarm instance);
    partial void DeleteIoT_SetAlarm(IoT_SetAlarm instance);
    partial void InsertIot_MeterAlarmPara(Iot_MeterAlarmPara instance);
    partial void UpdateIot_MeterAlarmPara(Iot_MeterAlarmPara instance);
    partial void DeleteIot_MeterAlarmPara(Iot_MeterAlarmPara instance);
    #endregion
		
		public AlarmDBDataContext() : 
				base(global::CY.IoTM.Common.Business.Properties.Settings.Default.IotMeterConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlarmDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IoT_AlarmInfo> IoT_AlarmInfo
		{
			get
			{
				return this.GetTable<IoT_AlarmInfo>();
			}
		}
		
		public System.Data.Linq.Table<View_AlarmInfo> View_AlarmInfo
		{
			get
			{
				return this.GetTable<View_AlarmInfo>();
			}
		}
		
		public System.Data.Linq.Table<View_AlarmMeter> View_AlarmMeter
		{
			get
			{
				return this.GetTable<View_AlarmMeter>();
			}
		}
		
		public System.Data.Linq.Table<IoT_AlarmMeter> IoT_AlarmMeter
		{
			get
			{
				return this.GetTable<IoT_AlarmMeter>();
			}
		}
		
		public System.Data.Linq.Table<IoT_SetAlarm> IoT_SetAlarm
		{
			get
			{
				return this.GetTable<IoT_SetAlarm>();
			}
		}
		
		public System.Data.Linq.Table<Iot_MeterAlarmPara> Iot_MeterAlarmPara
		{
			get
			{
				return this.GetTable<Iot_MeterAlarmPara>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_AlarmInfo")]
	public partial class IoT_AlarmInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<System.DateTime> _ReportDate;
		
		private string _Item;
		
		private string _AlarmValue;
		
		private System.Nullable<long> _MeterID;
		
		private string _MeterNo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnReportDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReportDateChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnAlarmValueChanging(string value);
    partial void OnAlarmValueChanged();
    partial void OnMeterIDChanging(System.Nullable<long> value);
    partial void OnMeterIDChanged();
    partial void OnMeterNoChanging(string value);
    partial void OnMeterNoChanged();
    #endregion
		
		public IoT_AlarmInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReportDate
		{
			get
			{
				return this._ReportDate;
			}
			set
			{
				if ((this._ReportDate != value))
				{
					this.OnReportDateChanging(value);
					this.SendPropertyChanging();
					this._ReportDate = value;
					this.SendPropertyChanged("ReportDate");
					this.OnReportDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="VarChar(50)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmValue", DbType="VarChar(50)")]
		public string AlarmValue
		{
			get
			{
				return this._AlarmValue;
			}
			set
			{
				if ((this._AlarmValue != value))
				{
					this.OnAlarmValueChanging(value);
					this.SendPropertyChanging();
					this._AlarmValue = value;
					this.SendPropertyChanged("AlarmValue");
					this.OnAlarmValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterID", DbType="BigInt")]
		public System.Nullable<long> MeterID
		{
			get
			{
				return this._MeterID;
			}
			set
			{
				if ((this._MeterID != value))
				{
					this.OnMeterIDChanging(value);
					this.SendPropertyChanging();
					this._MeterID = value;
					this.SendPropertyChanged("MeterID");
					this.OnMeterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="VarChar(20)")]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this.OnMeterNoChanging(value);
					this.SendPropertyChanging();
					this._MeterNo = value;
					this.SendPropertyChanged("MeterNo");
					this.OnMeterNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AlarmInfo")]
	public partial class View_AlarmInfo
	{
		
		private string _CompanyID;
		
		private string _UserID;
		
		private string _UserName;
		
		private string _Address;
		
		private string _MeterNo;
		
		private System.Nullable<System.DateTime> _ReportDate;
		
		private string _Item;
		
		private System.Nullable<long> _MeterID;
		
		private long _ID;
		
		private string _AlarmValue;
		
		public View_AlarmInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this._MeterNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReportDate
		{
			get
			{
				return this._ReportDate;
			}
			set
			{
				if ((this._ReportDate != value))
				{
					this._ReportDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="Char(2)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this._Item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterID", DbType="BigInt")]
		public System.Nullable<long> MeterID
		{
			get
			{
				return this._MeterID;
			}
			set
			{
				if ((this._MeterID != value))
				{
					this._MeterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlarmValue", DbType="VarChar(50)")]
		public string AlarmValue
		{
			get
			{
				return this._AlarmValue;
			}
			set
			{
				if ((this._AlarmValue != value))
				{
					this._AlarmValue = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AlarmMeter")]
	public partial class View_AlarmMeter
	{
		
		private string _CompanyID;
		
		private string _UserID;
		
		private string _UserName;
		
		private string _Address;
		
		private string _MeterNo;
		
		private System.Nullable<char> _State;
		
		private System.Nullable<System.DateTime> _FinishedDate;
		
		private string _Context;
		
		private long _ID;
		
		public View_AlarmMeter()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this._MeterNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(1)")]
		public System.Nullable<char> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishedDate
		{
			get
			{
				return this._FinishedDate;
			}
			set
			{
				if ((this._FinishedDate != value))
				{
					this._FinishedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(100)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this._Context = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_AlarmMeter")]
	public partial class IoT_AlarmMeter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _MeterID;
		
		private string _MeterNo;
		
		private System.Nullable<char> _State;
		
		private System.Nullable<System.DateTime> _FinishedDate;
		
		private string _Context;
		
		private string _TaskID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnMeterIDChanging(long value);
    partial void OnMeterIDChanged();
    partial void OnMeterNoChanging(string value);
    partial void OnMeterNoChanged();
    partial void OnStateChanging(System.Nullable<char> value);
    partial void OnStateChanged();
    partial void OnFinishedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishedDateChanged();
    partial void OnContextChanging(string value);
    partial void OnContextChanged();
    partial void OnTaskIDChanging(string value);
    partial void OnTaskIDChanged();
    #endregion
		
		public IoT_AlarmMeter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MeterID
		{
			get
			{
				return this._MeterID;
			}
			set
			{
				if ((this._MeterID != value))
				{
					this.OnMeterIDChanging(value);
					this.SendPropertyChanging();
					this._MeterID = value;
					this.SendPropertyChanged("MeterID");
					this.OnMeterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="VarChar(20)")]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this.OnMeterNoChanging(value);
					this.SendPropertyChanging();
					this._MeterNo = value;
					this.SendPropertyChanged("MeterNo");
					this.OnMeterNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(1)")]
		public System.Nullable<char> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishedDate
		{
			get
			{
				return this._FinishedDate;
			}
			set
			{
				if ((this._FinishedDate != value))
				{
					this.OnFinishedDateChanging(value);
					this.SendPropertyChanging();
					this._FinishedDate = value;
					this.SendPropertyChanged("FinishedDate");
					this.OnFinishedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(100)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this.OnContextChanging(value);
					this.SendPropertyChanging();
					this._Context = value;
					this.SendPropertyChanged("Context");
					this.OnContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskID", DbType="VarChar(50)")]
		public string TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_SetAlarm")]
	public partial class IoT_SetAlarm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<System.DateTime> _RegisterDate;
		
		private string _Scope;
		
		private System.Nullable<int> _Total;
		
		private System.Nullable<char> _State;
		
		private string _SwitchTag;
		
		private System.Nullable<int> _Par1;
		
		private System.Nullable<int> _Par2;
		
		private System.Nullable<int> _Par3;
		
		private string _Par4;
		
		private System.Nullable<int> _Par5;
		
		private System.Nullable<int> _Par6;
		
		private System.Nullable<int> _Par7;
		
		private System.Nullable<int> _Par8;
		
		private string _Par9;
		
		private string _Oper;
		
		private string _Context;
		
		private string _CompanyID;
		
		private string _TaskID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnRegisterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegisterDateChanged();
    partial void OnScopeChanging(string value);
    partial void OnScopeChanged();
    partial void OnTotalChanging(System.Nullable<int> value);
    partial void OnTotalChanged();
    partial void OnStateChanging(System.Nullable<char> value);
    partial void OnStateChanged();
    partial void OnSwitchTagChanging(string value);
    partial void OnSwitchTagChanged();
    partial void OnPar1Changing(System.Nullable<int> value);
    partial void OnPar1Changed();
    partial void OnPar2Changing(System.Nullable<int> value);
    partial void OnPar2Changed();
    partial void OnPar3Changing(System.Nullable<int> value);
    partial void OnPar3Changed();
    partial void OnPar4Changing(string value);
    partial void OnPar4Changed();
    partial void OnPar5Changing(System.Nullable<int> value);
    partial void OnPar5Changed();
    partial void OnPar6Changing(System.Nullable<int> value);
    partial void OnPar6Changed();
    partial void OnPar7Changing(System.Nullable<int> value);
    partial void OnPar7Changed();
    partial void OnPar8Changing(System.Nullable<int> value);
    partial void OnPar8Changed();
    partial void OnPar9Changing(string value);
    partial void OnPar9Changed();
    partial void OnOperChanging(string value);
    partial void OnOperChanged();
    partial void OnContextChanging(string value);
    partial void OnContextChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnTaskIDChanging(string value);
    partial void OnTaskIDChanged();
    #endregion
		
		public IoT_SetAlarm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegisterDate
		{
			get
			{
				return this._RegisterDate;
			}
			set
			{
				if ((this._RegisterDate != value))
				{
					this.OnRegisterDateChanging(value);
					this.SendPropertyChanging();
					this._RegisterDate = value;
					this.SendPropertyChanged("RegisterDate");
					this.OnRegisterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scope", DbType="VarChar(100)")]
		public string Scope
		{
			get
			{
				return this._Scope;
			}
			set
			{
				if ((this._Scope != value))
				{
					this.OnScopeChanging(value);
					this.SendPropertyChanging();
					this._Scope = value;
					this.SendPropertyChanged("Scope");
					this.OnScopeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(1)")]
		public System.Nullable<char> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SwitchTag", DbType="Char(16)")]
		public string SwitchTag
		{
			get
			{
				return this._SwitchTag;
			}
			set
			{
				if ((this._SwitchTag != value))
				{
					this.OnSwitchTagChanging(value);
					this.SendPropertyChanging();
					this._SwitchTag = value;
					this.SendPropertyChanged("SwitchTag");
					this.OnSwitchTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par1", DbType="Int")]
		public System.Nullable<int> Par1
		{
			get
			{
				return this._Par1;
			}
			set
			{
				if ((this._Par1 != value))
				{
					this.OnPar1Changing(value);
					this.SendPropertyChanging();
					this._Par1 = value;
					this.SendPropertyChanged("Par1");
					this.OnPar1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par2", DbType="Int")]
		public System.Nullable<int> Par2
		{
			get
			{
				return this._Par2;
			}
			set
			{
				if ((this._Par2 != value))
				{
					this.OnPar2Changing(value);
					this.SendPropertyChanging();
					this._Par2 = value;
					this.SendPropertyChanged("Par2");
					this.OnPar2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par3", DbType="Int")]
		public System.Nullable<int> Par3
		{
			get
			{
				return this._Par3;
			}
			set
			{
				if ((this._Par3 != value))
				{
					this.OnPar3Changing(value);
					this.SendPropertyChanging();
					this._Par3 = value;
					this.SendPropertyChanged("Par3");
					this.OnPar3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par4", DbType="Char(4)")]
		public string Par4
		{
			get
			{
				return this._Par4;
			}
			set
			{
				if ((this._Par4 != value))
				{
					this.OnPar4Changing(value);
					this.SendPropertyChanging();
					this._Par4 = value;
					this.SendPropertyChanged("Par4");
					this.OnPar4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par5", DbType="Int")]
		public System.Nullable<int> Par5
		{
			get
			{
				return this._Par5;
			}
			set
			{
				if ((this._Par5 != value))
				{
					this.OnPar5Changing(value);
					this.SendPropertyChanging();
					this._Par5 = value;
					this.SendPropertyChanged("Par5");
					this.OnPar5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par6", DbType="Int")]
		public System.Nullable<int> Par6
		{
			get
			{
				return this._Par6;
			}
			set
			{
				if ((this._Par6 != value))
				{
					this.OnPar6Changing(value);
					this.SendPropertyChanging();
					this._Par6 = value;
					this.SendPropertyChanged("Par6");
					this.OnPar6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par7", DbType="Int")]
		public System.Nullable<int> Par7
		{
			get
			{
				return this._Par7;
			}
			set
			{
				if ((this._Par7 != value))
				{
					this.OnPar7Changing(value);
					this.SendPropertyChanging();
					this._Par7 = value;
					this.SendPropertyChanged("Par7");
					this.OnPar7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par8", DbType="Int")]
		public System.Nullable<int> Par8
		{
			get
			{
				return this._Par8;
			}
			set
			{
				if ((this._Par8 != value))
				{
					this.OnPar8Changing(value);
					this.SendPropertyChanging();
					this._Par8 = value;
					this.SendPropertyChanged("Par8");
					this.OnPar8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par9", DbType="Char(2)")]
		public string Par9
		{
			get
			{
				return this._Par9;
			}
			set
			{
				if ((this._Par9 != value))
				{
					this.OnPar9Changing(value);
					this.SendPropertyChanging();
					this._Par9 = value;
					this.SendPropertyChanged("Par9");
					this.OnPar9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oper", DbType="VarChar(50)")]
		public string Oper
		{
			get
			{
				return this._Oper;
			}
			set
			{
				if ((this._Oper != value))
				{
					this.OnOperChanging(value);
					this.SendPropertyChanging();
					this._Oper = value;
					this.SendPropertyChanged("Oper");
					this.OnOperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(100)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this.OnContextChanging(value);
					this.SendPropertyChanging();
					this._Context = value;
					this.SendPropertyChanged("Context");
					this.OnContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaskID", DbType="VarChar(50)")]
		public string TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Iot_MeterAlarmPara")]
	public partial class Iot_MeterAlarmPara : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MeterNo;
		
		private string _SwitchTag;
		
		private System.Nullable<int> _Par1;
		
		private System.Nullable<int> _Par2;
		
		private System.Nullable<int> _Par3;
		
		private string _Par4;
		
		private System.Nullable<int> _Par5;
		
		private System.Nullable<int> _Par6;
		
		private System.Nullable<int> _Par7;
		
		private System.Nullable<int> _Par8;
		
		private string _Par9;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMeterNoChanging(string value);
    partial void OnMeterNoChanged();
    partial void OnSwitchTagChanging(string value);
    partial void OnSwitchTagChanged();
    partial void OnPar1Changing(System.Nullable<int> value);
    partial void OnPar1Changed();
    partial void OnPar2Changing(System.Nullable<int> value);
    partial void OnPar2Changed();
    partial void OnPar3Changing(System.Nullable<int> value);
    partial void OnPar3Changed();
    partial void OnPar4Changing(string value);
    partial void OnPar4Changed();
    partial void OnPar5Changing(System.Nullable<int> value);
    partial void OnPar5Changed();
    partial void OnPar6Changing(System.Nullable<int> value);
    partial void OnPar6Changed();
    partial void OnPar7Changing(System.Nullable<int> value);
    partial void OnPar7Changed();
    partial void OnPar8Changing(System.Nullable<int> value);
    partial void OnPar8Changed();
    partial void OnPar9Changing(string value);
    partial void OnPar9Changed();
    #endregion
		
		public Iot_MeterAlarmPara()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="VarChar(20)", IsPrimaryKey=true)]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this.OnMeterNoChanging(value);
					this.SendPropertyChanging();
					this._MeterNo = value;
					this.SendPropertyChanged("MeterNo");
					this.OnMeterNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SwitchTag", DbType="Char(16)")]
		public string SwitchTag
		{
			get
			{
				return this._SwitchTag;
			}
			set
			{
				if ((this._SwitchTag != value))
				{
					this.OnSwitchTagChanging(value);
					this.SendPropertyChanging();
					this._SwitchTag = value;
					this.SendPropertyChanged("SwitchTag");
					this.OnSwitchTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par1", DbType="Int")]
		public System.Nullable<int> Par1
		{
			get
			{
				return this._Par1;
			}
			set
			{
				if ((this._Par1 != value))
				{
					this.OnPar1Changing(value);
					this.SendPropertyChanging();
					this._Par1 = value;
					this.SendPropertyChanged("Par1");
					this.OnPar1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par2", DbType="Int")]
		public System.Nullable<int> Par2
		{
			get
			{
				return this._Par2;
			}
			set
			{
				if ((this._Par2 != value))
				{
					this.OnPar2Changing(value);
					this.SendPropertyChanging();
					this._Par2 = value;
					this.SendPropertyChanged("Par2");
					this.OnPar2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par3", DbType="Int")]
		public System.Nullable<int> Par3
		{
			get
			{
				return this._Par3;
			}
			set
			{
				if ((this._Par3 != value))
				{
					this.OnPar3Changing(value);
					this.SendPropertyChanging();
					this._Par3 = value;
					this.SendPropertyChanged("Par3");
					this.OnPar3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par4", DbType="Char(4)")]
		public string Par4
		{
			get
			{
				return this._Par4;
			}
			set
			{
				if ((this._Par4 != value))
				{
					this.OnPar4Changing(value);
					this.SendPropertyChanging();
					this._Par4 = value;
					this.SendPropertyChanged("Par4");
					this.OnPar4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par5", DbType="Int")]
		public System.Nullable<int> Par5
		{
			get
			{
				return this._Par5;
			}
			set
			{
				if ((this._Par5 != value))
				{
					this.OnPar5Changing(value);
					this.SendPropertyChanging();
					this._Par5 = value;
					this.SendPropertyChanged("Par5");
					this.OnPar5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par6", DbType="Int")]
		public System.Nullable<int> Par6
		{
			get
			{
				return this._Par6;
			}
			set
			{
				if ((this._Par6 != value))
				{
					this.OnPar6Changing(value);
					this.SendPropertyChanging();
					this._Par6 = value;
					this.SendPropertyChanged("Par6");
					this.OnPar6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par7", DbType="Int")]
		public System.Nullable<int> Par7
		{
			get
			{
				return this._Par7;
			}
			set
			{
				if ((this._Par7 != value))
				{
					this.OnPar7Changing(value);
					this.SendPropertyChanging();
					this._Par7 = value;
					this.SendPropertyChanged("Par7");
					this.OnPar7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par8", DbType="Int")]
		public System.Nullable<int> Par8
		{
			get
			{
				return this._Par8;
			}
			set
			{
				if ((this._Par8 != value))
				{
					this.OnPar8Changing(value);
					this.SendPropertyChanging();
					this._Par8 = value;
					this.SendPropertyChanged("Par8");
					this.OnPar8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Par9", DbType="Char(2)")]
		public string Par9
		{
			get
			{
				return this._Par9;
			}
			set
			{
				if ((this._Par9 != value))
				{
					this.OnPar9Changing(value);
					this.SendPropertyChanging();
					this._Par9 = value;
					this.SendPropertyChanged("Par9");
					this.OnPar9Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
