#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CY.IoTM.Common.Business
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IotMeter")]
	public partial class DataHistoryDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertIoT_DayReadMeter(IoT_DayReadMeter instance);
    partial void UpdateIoT_DayReadMeter(IoT_DayReadMeter instance);
    partial void DeleteIoT_DayReadMeter(IoT_DayReadMeter instance);
    partial void InsertIoT_MeterDataHistory(IoT_MeterDataHistory instance);
    partial void UpdateIoT_MeterDataHistory(IoT_MeterDataHistory instance);
    partial void DeleteIoT_MeterDataHistory(IoT_MeterDataHistory instance);
    #endregion
		
		public DataHistoryDBDataContext() : 
				base(global::CY.IoTM.Common.Business.Properties.Settings.Default.IotMeterConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataHistoryDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataHistoryDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataHistoryDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataHistoryDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IoT_DayReadMeter> IoT_DayReadMeter
		{
			get
			{
				return this.GetTable<IoT_DayReadMeter>();
			}
		}
		
		public System.Data.Linq.Table<IoT_MeterDataHistory> IoT_MeterDataHistory
		{
			get
			{
				return this.GetTable<IoT_MeterDataHistory>();
			}
		}
		
		public System.Data.Linq.Table<View_UserMeterHistory> View_UserMeterHistory
		{
			get
			{
				return this.GetTable<View_UserMeterHistory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_DayReadMeter")]
	public partial class IoT_DayReadMeter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _MeterID;
		
		private string _MeterNo;
		
		private System.Nullable<int> _Ser;
		
		private System.Nullable<decimal> _Gas;
		
		private System.Nullable<System.DateTime> _ReadDate;
		
		private System.Nullable<decimal> _RemainingAmount;
		
		private System.Nullable<decimal> _LastTotal;
		
		private string _ST1;
		
		private string _ST2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnMeterIDChanging(System.Nullable<long> value);
    partial void OnMeterIDChanged();
    partial void OnMeterNoChanging(string value);
    partial void OnMeterNoChanged();
    partial void OnSerChanging(System.Nullable<int> value);
    partial void OnSerChanged();
    partial void OnGasChanging(System.Nullable<decimal> value);
    partial void OnGasChanged();
    partial void OnReadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReadDateChanged();
    partial void OnRemainingAmountChanging(System.Nullable<decimal> value);
    partial void OnRemainingAmountChanged();
    partial void OnLastTotalChanging(System.Nullable<decimal> value);
    partial void OnLastTotalChanged();
    partial void OnST1Changing(string value);
    partial void OnST1Changed();
    partial void OnST2Changing(string value);
    partial void OnST2Changed();
    #endregion
		
		public IoT_DayReadMeter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterID", DbType="BigInt")]
		public System.Nullable<long> MeterID
		{
			get
			{
				return this._MeterID;
			}
			set
			{
				if ((this._MeterID != value))
				{
					this.OnMeterIDChanging(value);
					this.SendPropertyChanging();
					this._MeterID = value;
					this.SendPropertyChanged("MeterID");
					this.OnMeterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="Char(20)")]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this.OnMeterNoChanging(value);
					this.SendPropertyChanging();
					this._MeterNo = value;
					this.SendPropertyChanged("MeterNo");
					this.OnMeterNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ser", DbType="Int")]
		public System.Nullable<int> Ser
		{
			get
			{
				return this._Ser;
			}
			set
			{
				if ((this._Ser != value))
				{
					this.OnSerChanging(value);
					this.SendPropertyChanging();
					this._Ser = value;
					this.SendPropertyChanged("Ser");
					this.OnSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Gas
		{
			get
			{
				return this._Gas;
			}
			set
			{
				if ((this._Gas != value))
				{
					this.OnGasChanging(value);
					this.SendPropertyChanging();
					this._Gas = value;
					this.SendPropertyChanged("Gas");
					this.OnGasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReadDate
		{
			get
			{
				return this._ReadDate;
			}
			set
			{
				if ((this._ReadDate != value))
				{
					this.OnReadDateChanging(value);
					this.SendPropertyChanging();
					this._ReadDate = value;
					this.SendPropertyChanged("ReadDate");
					this.OnReadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainingAmount", DbType="Money")]
		public System.Nullable<decimal> RemainingAmount
		{
			get
			{
				return this._RemainingAmount;
			}
			set
			{
				if ((this._RemainingAmount != value))
				{
					this.OnRemainingAmountChanging(value);
					this.SendPropertyChanging();
					this._RemainingAmount = value;
					this.SendPropertyChanged("RemainingAmount");
					this.OnRemainingAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastTotal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LastTotal
		{
			get
			{
				return this._LastTotal;
			}
			set
			{
				if ((this._LastTotal != value))
				{
					this.OnLastTotalChanging(value);
					this.SendPropertyChanging();
					this._LastTotal = value;
					this.SendPropertyChanged("LastTotal");
					this.OnLastTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST1", DbType="Char(16)")]
		public string ST1
		{
			get
			{
				return this._ST1;
			}
			set
			{
				if ((this._ST1 != value))
				{
					this.OnST1Changing(value);
					this.SendPropertyChanging();
					this._ST1 = value;
					this.SendPropertyChanged("ST1");
					this.OnST1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST2", DbType="Char(8)")]
		public string ST2
		{
			get
			{
				return this._ST2;
			}
			set
			{
				if ((this._ST2 != value))
				{
					this.OnST2Changing(value);
					this.SendPropertyChanging();
					this._ST2 = value;
					this.SendPropertyChanged("ST2");
					this.OnST2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_MeterDataHistory")]
	public partial class IoT_MeterDataHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _MeterID;
		
		private string _MeterNo;
		
		private System.Nullable<int> _Ser;
		
		private System.Nullable<decimal> _Gas;
		
		private System.Nullable<System.DateTime> _ReadDate;
		
		private System.Nullable<decimal> _RemainingAmount;
		
		private System.Nullable<decimal> _LastTotal;
		
		private string _ST1;
		
		private string _ST2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnMeterIDChanging(System.Nullable<long> value);
    partial void OnMeterIDChanged();
    partial void OnMeterNoChanging(string value);
    partial void OnMeterNoChanged();
    partial void OnSerChanging(System.Nullable<int> value);
    partial void OnSerChanged();
    partial void OnGasChanging(System.Nullable<decimal> value);
    partial void OnGasChanged();
    partial void OnReadDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReadDateChanged();
    partial void OnRemainingAmountChanging(System.Nullable<decimal> value);
    partial void OnRemainingAmountChanged();
    partial void OnLastTotalChanging(System.Nullable<decimal> value);
    partial void OnLastTotalChanged();
    partial void OnST1Changing(string value);
    partial void OnST1Changed();
    partial void OnST2Changing(string value);
    partial void OnST2Changed();
    #endregion
		
		public IoT_MeterDataHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterID", DbType="BigInt")]
		public System.Nullable<long> MeterID
		{
			get
			{
				return this._MeterID;
			}
			set
			{
				if ((this._MeterID != value))
				{
					this.OnMeterIDChanging(value);
					this.SendPropertyChanging();
					this._MeterID = value;
					this.SendPropertyChanged("MeterID");
					this.OnMeterIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="VarChar(20)")]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this.OnMeterNoChanging(value);
					this.SendPropertyChanging();
					this._MeterNo = value;
					this.SendPropertyChanged("MeterNo");
					this.OnMeterNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ser", DbType="Int")]
		public System.Nullable<int> Ser
		{
			get
			{
				return this._Ser;
			}
			set
			{
				if ((this._Ser != value))
				{
					this.OnSerChanging(value);
					this.SendPropertyChanging();
					this._Ser = value;
					this.SendPropertyChanged("Ser");
					this.OnSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Gas
		{
			get
			{
				return this._Gas;
			}
			set
			{
				if ((this._Gas != value))
				{
					this.OnGasChanging(value);
					this.SendPropertyChanging();
					this._Gas = value;
					this.SendPropertyChanged("Gas");
					this.OnGasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReadDate
		{
			get
			{
				return this._ReadDate;
			}
			set
			{
				if ((this._ReadDate != value))
				{
					this.OnReadDateChanging(value);
					this.SendPropertyChanging();
					this._ReadDate = value;
					this.SendPropertyChanged("ReadDate");
					this.OnReadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainingAmount", DbType="Money")]
		public System.Nullable<decimal> RemainingAmount
		{
			get
			{
				return this._RemainingAmount;
			}
			set
			{
				if ((this._RemainingAmount != value))
				{
					this.OnRemainingAmountChanging(value);
					this.SendPropertyChanging();
					this._RemainingAmount = value;
					this.SendPropertyChanged("RemainingAmount");
					this.OnRemainingAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastTotal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LastTotal
		{
			get
			{
				return this._LastTotal;
			}
			set
			{
				if ((this._LastTotal != value))
				{
					this.OnLastTotalChanging(value);
					this.SendPropertyChanging();
					this._LastTotal = value;
					this.SendPropertyChanged("LastTotal");
					this.OnLastTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST1", DbType="Char(16)")]
		public string ST1
		{
			get
			{
				return this._ST1;
			}
			set
			{
				if ((this._ST1 != value))
				{
					this.OnST1Changing(value);
					this.SendPropertyChanging();
					this._ST1 = value;
					this.SendPropertyChanged("ST1");
					this.OnST1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST2", DbType="Char(8)")]
		public string ST2
		{
			get
			{
				return this._ST2;
			}
			set
			{
				if ((this._ST2 != value))
				{
					this.OnST2Changing(value);
					this.SendPropertyChanging();
					this._ST2 = value;
					this.SendPropertyChanged("ST2");
					this.OnST2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_UserMeterHistory")]
	public partial class View_UserMeterHistory
	{
		
		private string _CompanyID;
		
		private string _UserID;
		
		private string _UserName;
		
		private System.Nullable<char> _State;
		
		private string _Address;
		
		private string _Street;
		
		private string _Community;
		
		private string _Door;
		
		private string _MeterNo;
		
		private string _MeterType;
		
		private System.Nullable<char> _ValveState;
		
		private System.Nullable<decimal> _LastTotal;
		
		private System.Nullable<decimal> _TotalAmount;
		
		private System.Nullable<decimal> _RemainingAmount;
		
		private System.Nullable<System.DateTime> _ReadDate;
		
		private System.Nullable<System.DateTime> _InstallDate;
		
		private System.Nullable<decimal> _Gas;
		
		private string _ST1;
		
		public View_UserMeterHistory()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10)")]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(1)")]
		public System.Nullable<char> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="VarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Community", DbType="VarChar(50)")]
		public string Community
		{
			get
			{
				return this._Community;
			}
			set
			{
				if ((this._Community != value))
				{
					this._Community = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Door", DbType="VarChar(50)")]
		public string Door
		{
			get
			{
				return this._Door;
			}
			set
			{
				if ((this._Door != value))
				{
					this._Door = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="VarChar(20)")]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this._MeterNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterType", DbType="Char(2)")]
		public string MeterType
		{
			get
			{
				return this._MeterType;
			}
			set
			{
				if ((this._MeterType != value))
				{
					this._MeterType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValveState", DbType="Char(1)")]
		public System.Nullable<char> ValveState
		{
			get
			{
				return this._ValveState;
			}
			set
			{
				if ((this._ValveState != value))
				{
					this._ValveState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastTotal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> LastTotal
		{
			get
			{
				return this._LastTotal;
			}
			set
			{
				if ((this._LastTotal != value))
				{
					this._LastTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this._TotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemainingAmount", DbType="Money")]
		public System.Nullable<decimal> RemainingAmount
		{
			get
			{
				return this._RemainingAmount;
			}
			set
			{
				if ((this._RemainingAmount != value))
				{
					this._RemainingAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReadDate
		{
			get
			{
				return this._ReadDate;
			}
			set
			{
				if ((this._ReadDate != value))
				{
					this._ReadDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InstallDate
		{
			get
			{
				return this._InstallDate;
			}
			set
			{
				if ((this._InstallDate != value))
				{
					this._InstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Gas
		{
			get
			{
				return this._Gas;
			}
			set
			{
				if ((this._Gas != value))
				{
					this._Gas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST1", DbType="Char(16)")]
		public string ST1
		{
			get
			{
				return this._ST1;
			}
			set
			{
				if ((this._ST1 != value))
				{
					this._ST1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
