<?xml version="1.0" encoding="utf-8"?><Database Name="IotMeter" Class="SettlementDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=IotMeter;Integrated Security=True" SettingsObjectName="CY.IoTM.Common.Business.Properties.Settings" SettingsPropertyName="IotMeterConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IoT_SettlementDayMeter" Member="IoT_SettlementDayMeter">
    <Type Name="IoT_SettlementDayMeter">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MeterID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MeterNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="State" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FinishedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Context" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TaskID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_SettlementDayMeter" Member="View_SettlementDayMeter">
    <Type Name="View_SettlementDayMeter">
      <Column Name="CompanyID" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MeterNo" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FinishedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Context" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MeterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IoT_SetSettlementDay" Member="IoT_SetSettlementDay">
    <Type Name="IoT_SetSettlementDay">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Scope" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettlementDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettlementMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Oper" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Context" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="TaskID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_SettlementDayMeterView" Member="View_SettlementDayMeterView">
    <Type Name="View_SettlementDayMeterView">
      <Column Name="DayID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Scope" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettlementDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettlementMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Oper" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Context" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="TaskID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FailCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>