#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CY.IoTM.Common.Business
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IotMeter")]
	public partial class SystemDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertIoT_Street(IoT_Street instance);
    partial void UpdateIoT_Street(IoT_Street instance);
    partial void DeleteIoT_Street(IoT_Street instance);
    partial void InsertIoT_SystemPar(IoT_SystemPar instance);
    partial void UpdateIoT_SystemPar(IoT_SystemPar instance);
    partial void DeleteIoT_SystemPar(IoT_SystemPar instance);
    partial void InsertIoT_Community(IoT_Community instance);
    partial void UpdateIoT_Community(IoT_Community instance);
    partial void DeleteIoT_Community(IoT_Community instance);
    partial void InsertIoT_PricePar(IoT_PricePar instance);
    partial void UpdateIoT_PricePar(IoT_PricePar instance);
    partial void DeleteIoT_PricePar(IoT_PricePar instance);
    #endregion
		
		public SystemDBDataContext() : 
				base(global::CY.IoTM.Common.Business.Properties.Settings.Default.IotMeterConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SystemDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SystemDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IoT_Street> IoT_Street
		{
			get
			{
				return this.GetTable<IoT_Street>();
			}
		}
		
		public System.Data.Linq.Table<IoT_SystemPar> IoT_SystemPar
		{
			get
			{
				return this.GetTable<IoT_SystemPar>();
			}
		}
		
		public System.Data.Linq.Table<IoT_Community> IoT_Community
		{
			get
			{
				return this.GetTable<IoT_Community>();
			}
		}
		
		public System.Data.Linq.Table<View_Community> View_Community
		{
			get
			{
				return this.GetTable<View_Community>();
			}
		}
		
		public System.Data.Linq.Table<IoT_PricePar> IoT_PricePar
		{
			get
			{
				return this.GetTable<IoT_PricePar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_Street")]
	public partial class IoT_Street : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _CompanyID;
		
		private string _Ser;
		
		private string _Name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnSerChanging(string value);
    partial void OnSerChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public IoT_Street()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ser", DbType="VarChar(4)")]
		public string Ser
		{
			get
			{
				return this._Ser;
			}
			set
			{
				if ((this._Ser != value))
				{
					this.OnSerChanging(value);
					this.SendPropertyChanging();
					this._Ser = value;
					this.SendPropertyChanged("Ser");
					this.OnSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_SystemPar")]
	public partial class IoT_SystemPar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CompanyID;
		
		private System.Nullable<char> _ServerType;
		
		private string _NetAddr;
		
		private string _NetPort;
		
		private string _GSM;
		
		private string _APN;
		
		private string _UID;
		
		private string _PWD;
		
		private System.Nullable<bool> _AutoKey;
		
		private string _MKey;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnServerTypeChanging(System.Nullable<char> value);
    partial void OnServerTypeChanged();
    partial void OnNetAddrChanging(string value);
    partial void OnNetAddrChanged();
    partial void OnNetPortChanging(string value);
    partial void OnNetPortChanged();
    partial void OnGSMChanging(string value);
    partial void OnGSMChanged();
    partial void OnAPNChanging(string value);
    partial void OnAPNChanged();
    partial void OnUIDChanging(string value);
    partial void OnUIDChanged();
    partial void OnPWDChanging(string value);
    partial void OnPWDChanged();
    partial void OnAutoKeyChanging(System.Nullable<bool> value);
    partial void OnAutoKeyChanged();
    partial void OnMKeyChanging(string value);
    partial void OnMKeyChanged();
    #endregion
		
		public IoT_SystemPar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerType", DbType="Char(1)")]
		public System.Nullable<char> ServerType
		{
			get
			{
				return this._ServerType;
			}
			set
			{
				if ((this._ServerType != value))
				{
					this.OnServerTypeChanging(value);
					this.SendPropertyChanging();
					this._ServerType = value;
					this.SendPropertyChanged("ServerType");
					this.OnServerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetAddr", DbType="VarChar(25)")]
		public string NetAddr
		{
			get
			{
				return this._NetAddr;
			}
			set
			{
				if ((this._NetAddr != value))
				{
					this.OnNetAddrChanging(value);
					this.SendPropertyChanging();
					this._NetAddr = value;
					this.SendPropertyChanged("NetAddr");
					this.OnNetAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetPort", DbType="VarChar(5)")]
		public string NetPort
		{
			get
			{
				return this._NetPort;
			}
			set
			{
				if ((this._NetPort != value))
				{
					this.OnNetPortChanging(value);
					this.SendPropertyChanging();
					this._NetPort = value;
					this.SendPropertyChanged("NetPort");
					this.OnNetPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSM", DbType="VarChar(15)")]
		public string GSM
		{
			get
			{
				return this._GSM;
			}
			set
			{
				if ((this._GSM != value))
				{
					this.OnGSMChanging(value);
					this.SendPropertyChanging();
					this._GSM = value;
					this.SendPropertyChanged("GSM");
					this.OnGSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APN", DbType="VarChar(20)")]
		public string APN
		{
			get
			{
				return this._APN;
			}
			set
			{
				if ((this._APN != value))
				{
					this.OnAPNChanging(value);
					this.SendPropertyChanging();
					this._APN = value;
					this.SendPropertyChanged("APN");
					this.OnAPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", DbType="VarChar(10)")]
		public string UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PWD", DbType="VarChar(50)")]
		public string PWD
		{
			get
			{
				return this._PWD;
			}
			set
			{
				if ((this._PWD != value))
				{
					this.OnPWDChanging(value);
					this.SendPropertyChanging();
					this._PWD = value;
					this.SendPropertyChanged("PWD");
					this.OnPWDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoKey", DbType="Bit")]
		public System.Nullable<bool> AutoKey
		{
			get
			{
				return this._AutoKey;
			}
			set
			{
				if ((this._AutoKey != value))
				{
					this.OnAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._AutoKey = value;
					this.SendPropertyChanged("AutoKey");
					this.OnAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MKey", DbType="Char(16)")]
		public string MKey
		{
			get
			{
				return this._MKey;
			}
			set
			{
				if ((this._MKey != value))
				{
					this.OnMKeyChanging(value);
					this.SendPropertyChanging();
					this._MKey = value;
					this.SendPropertyChanged("MKey");
					this.OnMKeyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_Community")]
	public partial class IoT_Community : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _StreetID;
		
		private string _Ser;
		
		private string _Name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnStreetIDChanging(System.Nullable<long> value);
    partial void OnStreetIDChanged();
    partial void OnSerChanging(string value);
    partial void OnSerChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public IoT_Community()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetID", DbType="BigInt")]
		public System.Nullable<long> StreetID
		{
			get
			{
				return this._StreetID;
			}
			set
			{
				if ((this._StreetID != value))
				{
					this.OnStreetIDChanging(value);
					this.SendPropertyChanging();
					this._StreetID = value;
					this.SendPropertyChanged("StreetID");
					this.OnStreetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ser", DbType="VarChar(4)")]
		public string Ser
		{
			get
			{
				return this._Ser;
			}
			set
			{
				if ((this._Ser != value))
				{
					this.OnSerChanging(value);
					this.SendPropertyChanging();
					this._Ser = value;
					this.SendPropertyChanged("Ser");
					this.OnSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Community")]
	public partial class View_Community
	{
		
		private long _ID;
		
		private System.Nullable<long> _StreetID;
		
		private string _CommunityName;
		
		private string _StreetName;
		
		private string _CompanyID;
		
		private System.Nullable<int> _Num;
		
		private System.Nullable<int> _QLBNum;
		
		private System.Nullable<int> _JEBNum;
		
		public View_Community()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetID", DbType="BigInt")]
		public System.Nullable<long> StreetID
		{
			get
			{
				return this._StreetID;
			}
			set
			{
				if ((this._StreetID != value))
				{
					this._StreetID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommunityName", DbType="VarChar(50)")]
		public string CommunityName
		{
			get
			{
				return this._CommunityName;
			}
			set
			{
				if ((this._CommunityName != value))
				{
					this._CommunityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(50)")]
		public string StreetName
		{
			get
			{
				return this._StreetName;
			}
			set
			{
				if ((this._StreetName != value))
				{
					this._StreetName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num", DbType="Int")]
		public System.Nullable<int> Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this._Num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QLBNum", DbType="Int")]
		public System.Nullable<int> QLBNum
		{
			get
			{
				return this._QLBNum;
			}
			set
			{
				if ((this._QLBNum != value))
				{
					this._QLBNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JEBNum", DbType="Int")]
		public System.Nullable<int> JEBNum
		{
			get
			{
				return this._JEBNum;
			}
			set
			{
				if ((this._JEBNum != value))
				{
					this._JEBNum = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_PricePar")]
	public partial class IoT_PricePar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _CompanyID;
		
		private string _PriceName;
		
		private string _Ser;
		
		private System.Nullable<bool> _IsUsed;
		
		private System.Nullable<int> _Ladder;
		
		private string _SettlementType;
		
		private System.Nullable<int> _SettlementMonth;
		
		private System.Nullable<int> _SettlementDay;
		
		private System.Nullable<decimal> _Price1;
		
		private System.Nullable<decimal> _Gas1;
		
		private System.Nullable<decimal> _Price2;
		
		private System.Nullable<decimal> _Gas2;
		
		private System.Nullable<decimal> _Price3;
		
		private System.Nullable<decimal> _Gas3;
		
		private System.Nullable<decimal> _Price4;
		
		private System.Nullable<decimal> _Gas4;
		
		private System.Nullable<decimal> _Price5;
		
		private System.Nullable<System.DateTime> _PeriodStartDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnPriceNameChanging(string value);
    partial void OnPriceNameChanged();
    partial void OnSerChanging(string value);
    partial void OnSerChanged();
    partial void OnIsUsedChanging(System.Nullable<bool> value);
    partial void OnIsUsedChanged();
    partial void OnLadderChanging(System.Nullable<int> value);
    partial void OnLadderChanged();
    partial void OnSettlementTypeChanging(string value);
    partial void OnSettlementTypeChanged();
    partial void OnSettlementMonthChanging(System.Nullable<int> value);
    partial void OnSettlementMonthChanged();
    partial void OnSettlementDayChanging(System.Nullable<int> value);
    partial void OnSettlementDayChanged();
    partial void OnPrice1Changing(System.Nullable<decimal> value);
    partial void OnPrice1Changed();
    partial void OnGas1Changing(System.Nullable<decimal> value);
    partial void OnGas1Changed();
    partial void OnPrice2Changing(System.Nullable<decimal> value);
    partial void OnPrice2Changed();
    partial void OnGas2Changing(System.Nullable<decimal> value);
    partial void OnGas2Changed();
    partial void OnPrice3Changing(System.Nullable<decimal> value);
    partial void OnPrice3Changed();
    partial void OnGas3Changing(System.Nullable<decimal> value);
    partial void OnGas3Changed();
    partial void OnPrice4Changing(System.Nullable<decimal> value);
    partial void OnPrice4Changed();
    partial void OnGas4Changing(System.Nullable<decimal> value);
    partial void OnGas4Changed();
    partial void OnPrice5Changing(System.Nullable<decimal> value);
    partial void OnPrice5Changed();
    partial void OnPeriodStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPeriodStartDateChanged();
    #endregion
		
		public IoT_PricePar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceName", DbType="VarChar(50)")]
		public string PriceName
		{
			get
			{
				return this._PriceName;
			}
			set
			{
				if ((this._PriceName != value))
				{
					this.OnPriceNameChanging(value);
					this.SendPropertyChanging();
					this._PriceName = value;
					this.SendPropertyChanged("PriceName");
					this.OnPriceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ser", DbType="VarChar(4)")]
		public string Ser
		{
			get
			{
				return this._Ser;
			}
			set
			{
				if ((this._Ser != value))
				{
					this.OnSerChanging(value);
					this.SendPropertyChanging();
					this._Ser = value;
					this.SendPropertyChanged("Ser");
					this.OnSerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUsed", DbType="Bit")]
		public System.Nullable<bool> IsUsed
		{
			get
			{
				return this._IsUsed;
			}
			set
			{
				if ((this._IsUsed != value))
				{
					this.OnIsUsedChanging(value);
					this.SendPropertyChanging();
					this._IsUsed = value;
					this.SendPropertyChanged("IsUsed");
					this.OnIsUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ladder", DbType="Int")]
		public System.Nullable<int> Ladder
		{
			get
			{
				return this._Ladder;
			}
			set
			{
				if ((this._Ladder != value))
				{
					this.OnLadderChanging(value);
					this.SendPropertyChanging();
					this._Ladder = value;
					this.SendPropertyChanged("Ladder");
					this.OnLadderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettlementType", DbType="Char(2)")]
		public string SettlementType
		{
			get
			{
				return this._SettlementType;
			}
			set
			{
				if ((this._SettlementType != value))
				{
					this.OnSettlementTypeChanging(value);
					this.SendPropertyChanging();
					this._SettlementType = value;
					this.SendPropertyChanged("SettlementType");
					this.OnSettlementTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettlementMonth", DbType="Int")]
		public System.Nullable<int> SettlementMonth
		{
			get
			{
				return this._SettlementMonth;
			}
			set
			{
				if ((this._SettlementMonth != value))
				{
					this.OnSettlementMonthChanging(value);
					this.SendPropertyChanging();
					this._SettlementMonth = value;
					this.SendPropertyChanged("SettlementMonth");
					this.OnSettlementMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettlementDay", DbType="Int")]
		public System.Nullable<int> SettlementDay
		{
			get
			{
				return this._SettlementDay;
			}
			set
			{
				if ((this._SettlementDay != value))
				{
					this.OnSettlementDayChanging(value);
					this.SendPropertyChanging();
					this._SettlementDay = value;
					this.SendPropertyChanged("SettlementDay");
					this.OnSettlementDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price1", DbType="Money")]
		public System.Nullable<decimal> Price1
		{
			get
			{
				return this._Price1;
			}
			set
			{
				if ((this._Price1 != value))
				{
					this.OnPrice1Changing(value);
					this.SendPropertyChanging();
					this._Price1 = value;
					this.SendPropertyChanged("Price1");
					this.OnPrice1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas1", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Gas1
		{
			get
			{
				return this._Gas1;
			}
			set
			{
				if ((this._Gas1 != value))
				{
					this.OnGas1Changing(value);
					this.SendPropertyChanging();
					this._Gas1 = value;
					this.SendPropertyChanged("Gas1");
					this.OnGas1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price2", DbType="Money")]
		public System.Nullable<decimal> Price2
		{
			get
			{
				return this._Price2;
			}
			set
			{
				if ((this._Price2 != value))
				{
					this.OnPrice2Changing(value);
					this.SendPropertyChanging();
					this._Price2 = value;
					this.SendPropertyChanged("Price2");
					this.OnPrice2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Gas2
		{
			get
			{
				return this._Gas2;
			}
			set
			{
				if ((this._Gas2 != value))
				{
					this.OnGas2Changing(value);
					this.SendPropertyChanging();
					this._Gas2 = value;
					this.SendPropertyChanged("Gas2");
					this.OnGas2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price3", DbType="Money")]
		public System.Nullable<decimal> Price3
		{
			get
			{
				return this._Price3;
			}
			set
			{
				if ((this._Price3 != value))
				{
					this.OnPrice3Changing(value);
					this.SendPropertyChanging();
					this._Price3 = value;
					this.SendPropertyChanged("Price3");
					this.OnPrice3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas3", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Gas3
		{
			get
			{
				return this._Gas3;
			}
			set
			{
				if ((this._Gas3 != value))
				{
					this.OnGas3Changing(value);
					this.SendPropertyChanging();
					this._Gas3 = value;
					this.SendPropertyChanged("Gas3");
					this.OnGas3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price4", DbType="Money")]
		public System.Nullable<decimal> Price4
		{
			get
			{
				return this._Price4;
			}
			set
			{
				if ((this._Price4 != value))
				{
					this.OnPrice4Changing(value);
					this.SendPropertyChanging();
					this._Price4 = value;
					this.SendPropertyChanged("Price4");
					this.OnPrice4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gas4", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Gas4
		{
			get
			{
				return this._Gas4;
			}
			set
			{
				if ((this._Gas4 != value))
				{
					this.OnGas4Changing(value);
					this.SendPropertyChanging();
					this._Gas4 = value;
					this.SendPropertyChanged("Gas4");
					this.OnGas4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price5", DbType="Money")]
		public System.Nullable<decimal> Price5
		{
			get
			{
				return this._Price5;
			}
			set
			{
				if ((this._Price5 != value))
				{
					this.OnPrice5Changing(value);
					this.SendPropertyChanging();
					this._Price5 = value;
					this.SendPropertyChanged("Price5");
					this.OnPrice5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PeriodStartDate
		{
			get
			{
				return this._PeriodStartDate;
			}
			set
			{
				if ((this._PeriodStartDate != value))
				{
					this.OnPeriodStartDateChanging(value);
					this.SendPropertyChanging();
					this._PeriodStartDate = value;
					this.SendPropertyChanged("PeriodStartDate");
					this.OnPeriodStartDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
