<?xml version="1.0" encoding="utf-8"?><Database Name="IotMeter" Class="SystemDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=IotMeter;User ID=sa" SettingsObjectName="CY.IoTM.Common.Business.Properties.Settings" SettingsPropertyName="IotMeterConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IoT_Street" Member="IoT_Street">
    <Type Name="IoT_Street">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="Ser" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IoT_SystemPar" Member="IoT_SystemPar">
    <Type Name="IoT_SystemPar">
      <Column Name="CompanyID" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServerType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NetAddr" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="NetPort" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="GSM" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="APN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PWD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AutoKey" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MKey" Type="System.String" DbType="Char(16)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IoT_Community" Member="IoT_Community">
    <Type Name="IoT_Community">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StreetID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ser" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_Community" Member="View_Community">
    <Type Name="View_Community">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="StreetID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CommunityName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StreetName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="Num" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QLBNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JEBNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IoT_PricePar" Member="IoT_PricePar">
    <Type Name="IoT_PricePar">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="PriceName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ser" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="IsUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Ladder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettlementType" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="SettlementMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SettlementDay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Gas1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Price2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Gas2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Price3" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Gas3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Price4" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Gas4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Price5" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PeriodStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>