#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CY.IoTM.SystemInterface
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IotMeter")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertIoT_Meter(IoT_Meter instance);
    partial void UpdateIoT_Meter(IoT_Meter instance);
    partial void DeleteIoT_Meter(IoT_Meter instance);
    partial void InsertIoT_User(IoT_User instance);
    partial void UpdateIoT_User(IoT_User instance);
    partial void DeleteIoT_User(IoT_User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CY.IoTM.SystemInterface.Properties.Settings.Default.IotMeterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IoT_Meter> IoT_Meter
		{
			get
			{
				return this.GetTable<IoT_Meter>();
			}
		}
		
		public System.Data.Linq.Table<IoT_User> IoT_User
		{
			get
			{
				return this.GetTable<IoT_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_Meter")]
	public partial class IoT_Meter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _MeterNo;
		
		private string _Direction;
		
		private System.Nullable<System.DateTime> _InstallDate;
		
		private string _MeterModel;
		
		private string _MeterRange;
		
		private string _Installer;
		
		private string _IotPhone;
		
		private string _InstallType;
		
		private string _InstallPlace;
		
		private string _FDKH1;
		
		private string _FDKH2;
		
		private System.Nullable<bool> _InstallFDK;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnMeterNoChanging(string value);
    partial void OnMeterNoChanged();
    partial void OnDirectionChanging(string value);
    partial void OnDirectionChanged();
    partial void OnInstallDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInstallDateChanged();
    partial void OnMeterModelChanging(string value);
    partial void OnMeterModelChanged();
    partial void OnMeterRangeChanging(string value);
    partial void OnMeterRangeChanged();
    partial void OnInstallerChanging(string value);
    partial void OnInstallerChanged();
    partial void OnIotPhoneChanging(string value);
    partial void OnIotPhoneChanged();
    partial void OnInstallTypeChanging(string value);
    partial void OnInstallTypeChanged();
    partial void OnInstallPlaceChanging(string value);
    partial void OnInstallPlaceChanged();
    partial void OnFDKH1Changing(string value);
    partial void OnFDKH1Changed();
    partial void OnFDKH2Changing(string value);
    partial void OnFDKH2Changed();
    partial void OnInstallFDKChanging(System.Nullable<bool> value);
    partial void OnInstallFDKChanged();
    #endregion
		
		public IoT_Meter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this.OnMeterNoChanging(value);
					this.SendPropertyChanging();
					this._MeterNo = value;
					this.SendPropertyChanged("MeterNo");
					this.OnMeterNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direction", DbType="Char(4)")]
		public string Direction
		{
			get
			{
				return this._Direction;
			}
			set
			{
				if ((this._Direction != value))
				{
					this.OnDirectionChanging(value);
					this.SendPropertyChanging();
					this._Direction = value;
					this.SendPropertyChanged("Direction");
					this.OnDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InstallDate
		{
			get
			{
				return this._InstallDate;
			}
			set
			{
				if ((this._InstallDate != value))
				{
					this.OnInstallDateChanging(value);
					this.SendPropertyChanging();
					this._InstallDate = value;
					this.SendPropertyChanged("InstallDate");
					this.OnInstallDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterModel", DbType="NVarChar(50)")]
		public string MeterModel
		{
			get
			{
				return this._MeterModel;
			}
			set
			{
				if ((this._MeterModel != value))
				{
					this.OnMeterModelChanging(value);
					this.SendPropertyChanging();
					this._MeterModel = value;
					this.SendPropertyChanged("MeterModel");
					this.OnMeterModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterRange", DbType="NVarChar(50)")]
		public string MeterRange
		{
			get
			{
				return this._MeterRange;
			}
			set
			{
				if ((this._MeterRange != value))
				{
					this.OnMeterRangeChanging(value);
					this.SendPropertyChanging();
					this._MeterRange = value;
					this.SendPropertyChanged("MeterRange");
					this.OnMeterRangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Installer", DbType="NVarChar(50)")]
		public string Installer
		{
			get
			{
				return this._Installer;
			}
			set
			{
				if ((this._Installer != value))
				{
					this.OnInstallerChanging(value);
					this.SendPropertyChanging();
					this._Installer = value;
					this.SendPropertyChanged("Installer");
					this.OnInstallerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IotPhone", DbType="NVarChar(50)")]
		public string IotPhone
		{
			get
			{
				return this._IotPhone;
			}
			set
			{
				if ((this._IotPhone != value))
				{
					this.OnIotPhoneChanging(value);
					this.SendPropertyChanging();
					this._IotPhone = value;
					this.SendPropertyChanged("IotPhone");
					this.OnIotPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallType", DbType="NVarChar(50)")]
		public string InstallType
		{
			get
			{
				return this._InstallType;
			}
			set
			{
				if ((this._InstallType != value))
				{
					this.OnInstallTypeChanging(value);
					this.SendPropertyChanging();
					this._InstallType = value;
					this.SendPropertyChanged("InstallType");
					this.OnInstallTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallPlace", DbType="NVarChar(50)")]
		public string InstallPlace
		{
			get
			{
				return this._InstallPlace;
			}
			set
			{
				if ((this._InstallPlace != value))
				{
					this.OnInstallPlaceChanging(value);
					this.SendPropertyChanging();
					this._InstallPlace = value;
					this.SendPropertyChanged("InstallPlace");
					this.OnInstallPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDKH1", DbType="NChar(10)")]
		public string FDKH1
		{
			get
			{
				return this._FDKH1;
			}
			set
			{
				if ((this._FDKH1 != value))
				{
					this.OnFDKH1Changing(value);
					this.SendPropertyChanging();
					this._FDKH1 = value;
					this.SendPropertyChanged("FDKH1");
					this.OnFDKH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDKH2", DbType="NChar(10)")]
		public string FDKH2
		{
			get
			{
				return this._FDKH2;
			}
			set
			{
				if ((this._FDKH2 != value))
				{
					this.OnFDKH2Changing(value);
					this.SendPropertyChanging();
					this._FDKH2 = value;
					this.SendPropertyChanged("FDKH2");
					this.OnFDKH2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallFDK", DbType="Bit")]
		public System.Nullable<bool> InstallFDK
		{
			get
			{
				return this._InstallFDK;
			}
			set
			{
				if ((this._InstallFDK != value))
				{
					this.OnInstallFDKChanging(value);
					this.SendPropertyChanging();
					this._InstallFDK = value;
					this.SendPropertyChanged("InstallFDK");
					this.OnInstallFDKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IoT_User")]
	public partial class IoT_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _UserName;
		
		private string _Phone;
		
		private string _Street;
		
		private string _Community;
		
		private string _Door;
		
		private string _Address;
		
		private string _UserType;
		
		private string _SFZH;
		
		private string _BZRQ;
		
		private System.Nullable<decimal> _BZFY;
		
		private System.Nullable<bool> _YJBZFY;
		
		private string _LD;
		
		private string _DY;
		
		private System.Nullable<bool> _BGL;
		
		private System.Nullable<bool> _ZS;
		
		private System.Nullable<bool> _YGBX;
		
		private System.Nullable<System.DateTime> _BXGMRQ;
		
		private System.Nullable<int> _BXYXQ;
		
		private string _BXGMRSFZ;
		
		private System.Nullable<bool> _YQHTQD;
		
		private System.Nullable<System.DateTime> _YQHTQDRQ;
		
		private string _YQHTBH;
		
		private string _FYQHTR;
		
		private string _QYQHTR;
		
		private string _BZCZYBH;
		
		private System.Nullable<bool> _SYBWG;
		
		private System.Nullable<int> _BWGCD;
		
		private string _SF_UserId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnCommunityChanging(string value);
    partial void OnCommunityChanged();
    partial void OnDoorChanging(string value);
    partial void OnDoorChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnSFZHChanging(string value);
    partial void OnSFZHChanged();
    partial void OnBZRQChanging(string value);
    partial void OnBZRQChanged();
    partial void OnBZFYChanging(System.Nullable<decimal> value);
    partial void OnBZFYChanged();
    partial void OnYJBZFYChanging(System.Nullable<bool> value);
    partial void OnYJBZFYChanged();
    partial void OnLDChanging(string value);
    partial void OnLDChanged();
    partial void OnDYChanging(string value);
    partial void OnDYChanged();
    partial void OnBGLChanging(System.Nullable<bool> value);
    partial void OnBGLChanged();
    partial void OnZSChanging(System.Nullable<bool> value);
    partial void OnZSChanged();
    partial void OnYGBXChanging(System.Nullable<bool> value);
    partial void OnYGBXChanged();
    partial void OnBXGMRQChanging(System.Nullable<System.DateTime> value);
    partial void OnBXGMRQChanged();
    partial void OnBXYXQChanging(System.Nullable<int> value);
    partial void OnBXYXQChanged();
    partial void OnBXGMRSFZChanging(string value);
    partial void OnBXGMRSFZChanged();
    partial void OnYQHTQDChanging(System.Nullable<bool> value);
    partial void OnYQHTQDChanged();
    partial void OnYQHTQDRQChanging(System.Nullable<System.DateTime> value);
    partial void OnYQHTQDRQChanged();
    partial void OnYQHTBHChanging(string value);
    partial void OnYQHTBHChanged();
    partial void OnFYQHTRChanging(string value);
    partial void OnFYQHTRChanged();
    partial void OnQYQHTRChanging(string value);
    partial void OnQYQHTRChanged();
    partial void OnBZCZYBHChanging(string value);
    partial void OnBZCZYBHChanged();
    partial void OnSYBWGChanging(System.Nullable<bool> value);
    partial void OnSYBWGChanged();
    partial void OnBWGCDChanging(System.Nullable<int> value);
    partial void OnBWGCDChanged();
    partial void OnSF_UserIdChanging(string value);
    partial void OnSF_UserIdChanged();
    #endregion
		
		public IoT_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="VarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Community", DbType="VarChar(50)")]
		public string Community
		{
			get
			{
				return this._Community;
			}
			set
			{
				if ((this._Community != value))
				{
					this.OnCommunityChanging(value);
					this.SendPropertyChanging();
					this._Community = value;
					this.SendPropertyChanged("Community");
					this.OnCommunityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Door", DbType="VarChar(50)")]
		public string Door
		{
			get
			{
				return this._Door;
			}
			set
			{
				if ((this._Door != value))
				{
					this.OnDoorChanging(value);
					this.SendPropertyChanging();
					this._Door = value;
					this.SendPropertyChanged("Door");
					this.OnDoorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(2)")]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SFZH", DbType="VarChar(50)")]
		public string SFZH
		{
			get
			{
				return this._SFZH;
			}
			set
			{
				if ((this._SFZH != value))
				{
					this.OnSFZHChanging(value);
					this.SendPropertyChanging();
					this._SFZH = value;
					this.SendPropertyChanged("SFZH");
					this.OnSFZHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZRQ", DbType="NVarChar(50)")]
		public string BZRQ
		{
			get
			{
				return this._BZRQ;
			}
			set
			{
				if ((this._BZRQ != value))
				{
					this.OnBZRQChanging(value);
					this.SendPropertyChanging();
					this._BZRQ = value;
					this.SendPropertyChanged("BZRQ");
					this.OnBZRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZFY", DbType="Money")]
		public System.Nullable<decimal> BZFY
		{
			get
			{
				return this._BZFY;
			}
			set
			{
				if ((this._BZFY != value))
				{
					this.OnBZFYChanging(value);
					this.SendPropertyChanging();
					this._BZFY = value;
					this.SendPropertyChanged("BZFY");
					this.OnBZFYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YJBZFY", DbType="Bit")]
		public System.Nullable<bool> YJBZFY
		{
			get
			{
				return this._YJBZFY;
			}
			set
			{
				if ((this._YJBZFY != value))
				{
					this.OnYJBZFYChanging(value);
					this.SendPropertyChanging();
					this._YJBZFY = value;
					this.SendPropertyChanged("YJBZFY");
					this.OnYJBZFYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LD", DbType="NVarChar(50)")]
		public string LD
		{
			get
			{
				return this._LD;
			}
			set
			{
				if ((this._LD != value))
				{
					this.OnLDChanging(value);
					this.SendPropertyChanging();
					this._LD = value;
					this.SendPropertyChanged("LD");
					this.OnLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DY", DbType="NVarChar(50)")]
		public string DY
		{
			get
			{
				return this._DY;
			}
			set
			{
				if ((this._DY != value))
				{
					this.OnDYChanging(value);
					this.SendPropertyChanging();
					this._DY = value;
					this.SendPropertyChanged("DY");
					this.OnDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BGL", DbType="Bit")]
		public System.Nullable<bool> BGL
		{
			get
			{
				return this._BGL;
			}
			set
			{
				if ((this._BGL != value))
				{
					this.OnBGLChanging(value);
					this.SendPropertyChanging();
					this._BGL = value;
					this.SendPropertyChanged("BGL");
					this.OnBGLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZS", DbType="Bit")]
		public System.Nullable<bool> ZS
		{
			get
			{
				return this._ZS;
			}
			set
			{
				if ((this._ZS != value))
				{
					this.OnZSChanging(value);
					this.SendPropertyChanging();
					this._ZS = value;
					this.SendPropertyChanged("ZS");
					this.OnZSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YGBX", DbType="Bit")]
		public System.Nullable<bool> YGBX
		{
			get
			{
				return this._YGBX;
			}
			set
			{
				if ((this._YGBX != value))
				{
					this.OnYGBXChanging(value);
					this.SendPropertyChanging();
					this._YGBX = value;
					this.SendPropertyChanged("YGBX");
					this.OnYGBXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BXGMRQ", DbType="Date")]
		public System.Nullable<System.DateTime> BXGMRQ
		{
			get
			{
				return this._BXGMRQ;
			}
			set
			{
				if ((this._BXGMRQ != value))
				{
					this.OnBXGMRQChanging(value);
					this.SendPropertyChanging();
					this._BXGMRQ = value;
					this.SendPropertyChanged("BXGMRQ");
					this.OnBXGMRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BXYXQ", DbType="Int")]
		public System.Nullable<int> BXYXQ
		{
			get
			{
				return this._BXYXQ;
			}
			set
			{
				if ((this._BXYXQ != value))
				{
					this.OnBXYXQChanging(value);
					this.SendPropertyChanging();
					this._BXYXQ = value;
					this.SendPropertyChanged("BXYXQ");
					this.OnBXYXQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BXGMRSFZ", DbType="NVarChar(50)")]
		public string BXGMRSFZ
		{
			get
			{
				return this._BXGMRSFZ;
			}
			set
			{
				if ((this._BXGMRSFZ != value))
				{
					this.OnBXGMRSFZChanging(value);
					this.SendPropertyChanging();
					this._BXGMRSFZ = value;
					this.SendPropertyChanged("BXGMRSFZ");
					this.OnBXGMRSFZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YQHTQD", DbType="Bit")]
		public System.Nullable<bool> YQHTQD
		{
			get
			{
				return this._YQHTQD;
			}
			set
			{
				if ((this._YQHTQD != value))
				{
					this.OnYQHTQDChanging(value);
					this.SendPropertyChanging();
					this._YQHTQD = value;
					this.SendPropertyChanged("YQHTQD");
					this.OnYQHTQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YQHTQDRQ", DbType="Date")]
		public System.Nullable<System.DateTime> YQHTQDRQ
		{
			get
			{
				return this._YQHTQDRQ;
			}
			set
			{
				if ((this._YQHTQDRQ != value))
				{
					this.OnYQHTQDRQChanging(value);
					this.SendPropertyChanging();
					this._YQHTQDRQ = value;
					this.SendPropertyChanged("YQHTQDRQ");
					this.OnYQHTQDRQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YQHTBH", DbType="NVarChar(50)")]
		public string YQHTBH
		{
			get
			{
				return this._YQHTBH;
			}
			set
			{
				if ((this._YQHTBH != value))
				{
					this.OnYQHTBHChanging(value);
					this.SendPropertyChanging();
					this._YQHTBH = value;
					this.SendPropertyChanged("YQHTBH");
					this.OnYQHTBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FYQHTR", DbType="NVarChar(50)")]
		public string FYQHTR
		{
			get
			{
				return this._FYQHTR;
			}
			set
			{
				if ((this._FYQHTR != value))
				{
					this.OnFYQHTRChanging(value);
					this.SendPropertyChanging();
					this._FYQHTR = value;
					this.SendPropertyChanged("FYQHTR");
					this.OnFYQHTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QYQHTR", DbType="NVarChar(50)")]
		public string QYQHTR
		{
			get
			{
				return this._QYQHTR;
			}
			set
			{
				if ((this._QYQHTR != value))
				{
					this.OnQYQHTRChanging(value);
					this.SendPropertyChanging();
					this._QYQHTR = value;
					this.SendPropertyChanged("QYQHTR");
					this.OnQYQHTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BZCZYBH", DbType="NVarChar(50)")]
		public string BZCZYBH
		{
			get
			{
				return this._BZCZYBH;
			}
			set
			{
				if ((this._BZCZYBH != value))
				{
					this.OnBZCZYBHChanging(value);
					this.SendPropertyChanging();
					this._BZCZYBH = value;
					this.SendPropertyChanged("BZCZYBH");
					this.OnBZCZYBHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYBWG", DbType="Bit")]
		public System.Nullable<bool> SYBWG
		{
			get
			{
				return this._SYBWG;
			}
			set
			{
				if ((this._SYBWG != value))
				{
					this.OnSYBWGChanging(value);
					this.SendPropertyChanging();
					this._SYBWG = value;
					this.SendPropertyChanged("SYBWG");
					this.OnSYBWGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BWGCD", DbType="Int")]
		public System.Nullable<int> BWGCD
		{
			get
			{
				return this._BWGCD;
			}
			set
			{
				if ((this._BWGCD != value))
				{
					this.OnBWGCDChanging(value);
					this.SendPropertyChanging();
					this._BWGCD = value;
					this.SendPropertyChanged("BWGCD");
					this.OnBWGCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SF_UserId", DbType="NVarChar(50)")]
		public string SF_UserId
		{
			get
			{
				return this._SF_UserId;
			}
			set
			{
				if ((this._SF_UserId != value))
				{
					this.OnSF_UserIdChanging(value);
					this.SendPropertyChanging();
					this._SF_UserId = value;
					this.SendPropertyChanged("SF_UserId");
					this.OnSF_UserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
