
--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期二, 29 三月, 2016 
--   DBMS       : SQL Server 2008 
--   -------------------------------------------------- 



--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADContext') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADContext;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADItem') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADItem;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADPublish') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADPublish;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADPublishUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADPublishUser;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADUser;
GO

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期四, 31 三月, 2016 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADPublishUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADPublishUser;
GO

--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期二, 05 四月, 2016 
--   DBMS       : SQL Server 2008 
--   -------------------------------------------------- 



--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADContext') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADContext;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADItem') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADItem;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADPublish') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADPublish;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADPublishUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADPublishUser;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADUser;
GO

--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期三, 06 四月, 2016 
--   DBMS       : SQL Server 2008 
--   -------------------------------------------------- 



--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADContext') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADContext;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADItem') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADItem;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADPublish') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADPublish;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADPublishUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADPublishUser;
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADUser;
GO

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期四, 14 四月, 2016 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ADUser') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ADUser;
GO

USE [IotMeter]
GO

/****** Object:  View [dbo].[View_AdPublish]    Script Date: 04/19/2016 17:42:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [IotMeter]
GO

/****** Object:  View [dbo].[View_AdPublishUserInfo]    Script Date: 04/19/2016 16:44:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [IotMeter]
GO

/****** Object:  View [dbo].[View_AdPublishUserInfo]    Script Date: 04/19/2016 16:44:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [IotMeter]
GO

/****** Object:  View [dbo].[View_AdPublishUserInfo]    Script Date: 04/25/2016 21:56:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [IotMeter]
GO

/****** Object:  View [dbo].[View_UserInfo]    Script Date: 04/26/2016 17:02:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [IotMeter]
GO

/****** Object:  View [dbo].[View_UserInfoADD]    Script Date: 04/26/2016 17:02:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [IotMeter]
GO

/****** Object:  View [dbo].[View_UserInfoADDC]    Script Date: 04/26/2016 17:02:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期五, 06 五月, 2016 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Iot_MeterAlarmPara') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Iot_MeterAlarmPara;
GO

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期五, 06 五月, 2016 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Iot_MeterAlarmPara') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Iot_MeterAlarmPara;
GO

--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期五, 06 五月, 2016 
--  DBMS       : SQL Server 2008 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Iot_MeterAlarmPara') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Iot_MeterAlarmPara;
GO
