#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CY.IoTM.Common.ADSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IotMeter")]
	public partial class AdMeterDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertADContext(ADContext instance);
    partial void UpdateADContext(ADContext instance);
    partial void DeleteADContext(ADContext instance);
    partial void InsertADPublish(ADPublish instance);
    partial void UpdateADPublish(ADPublish instance);
    partial void DeleteADPublish(ADPublish instance);
    partial void InsertADPublishUser(ADPublishUser instance);
    partial void UpdateADPublishUser(ADPublishUser instance);
    partial void DeleteADPublishUser(ADPublishUser instance);
    partial void InsertADItem(ADItem instance);
    partial void UpdateADItem(ADItem instance);
    partial void DeleteADItem(ADItem instance);
    partial void InsertADUser(ADUser instance);
    partial void UpdateADUser(ADUser instance);
    partial void DeleteADUser(ADUser instance);
    #endregion
		
		public AdMeterDBDataContext() : 
				base(global::CY.IoTM.Common.ADSystem.Properties.Settings.Default.IotMeterConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AdMeterDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdMeterDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdMeterDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdMeterDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADContext> ADContext
		{
			get
			{
				return this.GetTable<ADContext>();
			}
		}
		
		public System.Data.Linq.Table<ADPublish> ADPublish
		{
			get
			{
				return this.GetTable<ADPublish>();
			}
		}
		
		public System.Data.Linq.Table<ADPublishUser> ADPublishUser
		{
			get
			{
				return this.GetTable<ADPublishUser>();
			}
		}
		
		public System.Data.Linq.Table<ADItem> ADItem
		{
			get
			{
				return this.GetTable<ADItem>();
			}
		}
		
		public System.Data.Linq.Table<View_AdUser> View_AdUser
		{
			get
			{
				return this.GetTable<View_AdUser>();
			}
		}
		
		public System.Data.Linq.Table<ADUser> ADUser
		{
			get
			{
				return this.GetTable<ADUser>();
			}
		}
		
		public System.Data.Linq.Table<View_UserInfo> View_UserInfo
		{
			get
			{
				return this.GetTable<View_UserInfo>();
			}
		}
		
		public System.Data.Linq.Table<View_AdPublish> View_AdPublish
		{
			get
			{
				return this.GetTable<View_AdPublish>();
			}
		}
		
		public System.Data.Linq.Table<View_AdPublishUserInfo> View_AdPublishUserInfo
		{
			get
			{
				return this.GetTable<View_AdPublishUserInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADContext")]
	public partial class ADContext : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AC_ID;
		
		private string _CompanyID;
		
		private string _Context;
		
		private System.Nullable<short> _State;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAC_IDChanging(long value);
    partial void OnAC_IDChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnContextChanging(string value);
    partial void OnContextChanged();
    partial void OnStateChanging(System.Nullable<short> value);
    partial void OnStateChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
		
		public ADContext()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long AC_ID
		{
			get
			{
				return this._AC_ID;
			}
			set
			{
				if ((this._AC_ID != value))
				{
					this.OnAC_IDChanging(value);
					this.SendPropertyChanging();
					this._AC_ID = value;
					this.SendPropertyChanged("AC_ID");
					this.OnAC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(200)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this.OnContextChanging(value);
					this.SendPropertyChanging();
					this._Context = value;
					this.SendPropertyChanged("Context");
					this.OnContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="SmallInt")]
		public System.Nullable<short> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADPublish")]
	public partial class ADPublish : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AP_ID;
		
		private string _CompanyID;
		
		private System.Nullable<long> _AC_ID;
		
		private string _AreaContext;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private System.Nullable<int> _UserCount;
		
		private System.Nullable<short> _State;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAP_IDChanging(long value);
    partial void OnAP_IDChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnAC_IDChanging(System.Nullable<long> value);
    partial void OnAC_IDChanged();
    partial void OnAreaContextChanging(string value);
    partial void OnAreaContextChanged();
    partial void OnPublishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishDateChanged();
    partial void OnUserCountChanging(System.Nullable<int> value);
    partial void OnUserCountChanged();
    partial void OnStateChanging(System.Nullable<short> value);
    partial void OnStateChanged();
    #endregion
		
		public ADPublish()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long AP_ID
		{
			get
			{
				return this._AP_ID;
			}
			set
			{
				if ((this._AP_ID != value))
				{
					this.OnAP_IDChanging(value);
					this.SendPropertyChanging();
					this._AP_ID = value;
					this.SendPropertyChanged("AP_ID");
					this.OnAP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_ID", DbType="BigInt")]
		public System.Nullable<long> AC_ID
		{
			get
			{
				return this._AC_ID;
			}
			set
			{
				if ((this._AC_ID != value))
				{
					this.OnAC_IDChanging(value);
					this.SendPropertyChanging();
					this._AC_ID = value;
					this.SendPropertyChanged("AC_ID");
					this.OnAC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaContext", DbType="VarChar(200)")]
		public string AreaContext
		{
			get
			{
				return this._AreaContext;
			}
			set
			{
				if ((this._AreaContext != value))
				{
					this.OnAreaContextChanging(value);
					this.SendPropertyChanging();
					this._AreaContext = value;
					this.SendPropertyChanged("AreaContext");
					this.OnAreaContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this.OnPublishDateChanging(value);
					this.SendPropertyChanging();
					this._PublishDate = value;
					this.SendPropertyChanged("PublishDate");
					this.OnPublishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCount", DbType="Int")]
		public System.Nullable<int> UserCount
		{
			get
			{
				return this._UserCount;
			}
			set
			{
				if ((this._UserCount != value))
				{
					this.OnUserCountChanging(value);
					this.SendPropertyChanging();
					this._UserCount = value;
					this.SendPropertyChanged("UserCount");
					this.OnUserCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="SmallInt")]
		public System.Nullable<short> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADPublishUser")]
	public partial class ADPublishUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _AP_ID;
		
		private string _UserID;
		
		private string _CompanyID;
		
		private System.Nullable<short> _State;
		
		private System.Nullable<System.DateTime> _FinishedDate;
		
		private string _Context;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnAP_IDChanging(long value);
    partial void OnAP_IDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnStateChanging(System.Nullable<short> value);
    partial void OnStateChanged();
    partial void OnFinishedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFinishedDateChanged();
    partial void OnContextChanging(string value);
    partial void OnContextChanged();
    #endregion
		
		public ADPublishUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long AP_ID
		{
			get
			{
				return this._AP_ID;
			}
			set
			{
				if ((this._AP_ID != value))
				{
					this.OnAP_IDChanging(value);
					this.SendPropertyChanging();
					this._AP_ID = value;
					this.SendPropertyChanged("AP_ID");
					this.OnAP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="SmallInt")]
		public System.Nullable<short> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishedDate
		{
			get
			{
				return this._FinishedDate;
			}
			set
			{
				if ((this._FinishedDate != value))
				{
					this.OnFinishedDateChanging(value);
					this.SendPropertyChanging();
					this._FinishedDate = value;
					this.SendPropertyChanged("FinishedDate");
					this.OnFinishedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(MAX)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this.OnContextChanging(value);
					this.SendPropertyChanging();
					this._Context = value;
					this.SendPropertyChanged("Context");
					this.OnContextChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADItem")]
	public partial class ADItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _AI_ID;
		
		private System.Nullable<long> _AC_ID;
		
		private System.Nullable<short> _OrderID;
		
		private string _FileName;
		
		private System.Nullable<System.DateTime> _BDate;
		
		private System.Nullable<System.DateTime> _EDate;
		
		private System.Nullable<short> _Length;
		
		private string _StoreName;
		
		private System.Nullable<bool> _IsDisplay;
		
		private string _StorePath;
		
		private System.Nullable<int> _FileLength;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAI_IDChanging(long value);
    partial void OnAI_IDChanged();
    partial void OnAC_IDChanging(System.Nullable<long> value);
    partial void OnAC_IDChanged();
    partial void OnOrderIDChanging(System.Nullable<short> value);
    partial void OnOrderIDChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnBDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBDateChanged();
    partial void OnEDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEDateChanged();
    partial void OnLengthChanging(System.Nullable<short> value);
    partial void OnLengthChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnIsDisplayChanging(System.Nullable<bool> value);
    partial void OnIsDisplayChanged();
    partial void OnStorePathChanging(string value);
    partial void OnStorePathChanged();
    partial void OnFileLengthChanging(System.Nullable<int> value);
    partial void OnFileLengthChanged();
    #endregion
		
		public ADItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AI_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long AI_ID
		{
			get
			{
				return this._AI_ID;
			}
			set
			{
				if ((this._AI_ID != value))
				{
					this.OnAI_IDChanging(value);
					this.SendPropertyChanging();
					this._AI_ID = value;
					this.SendPropertyChanged("AI_ID");
					this.OnAI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_ID", DbType="BigInt")]
		public System.Nullable<long> AC_ID
		{
			get
			{
				return this._AC_ID;
			}
			set
			{
				if ((this._AC_ID != value))
				{
					this.OnAC_IDChanging(value);
					this.SendPropertyChanging();
					this._AC_ID = value;
					this.SendPropertyChanged("AC_ID");
					this.OnAC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderID", DbType="SmallInt")]
		public System.Nullable<short> OrderID
		{
			get
			{
				return this._OrderID;
			}
			set
			{
				if ((this._OrderID != value))
				{
					this.OnOrderIDChanging(value);
					this.SendPropertyChanging();
					this._OrderID = value;
					this.SendPropertyChanged("OrderID");
					this.OnOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(20)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> BDate
		{
			get
			{
				return this._BDate;
			}
			set
			{
				if ((this._BDate != value))
				{
					this.OnBDateChanging(value);
					this.SendPropertyChanging();
					this._BDate = value;
					this.SendPropertyChanged("BDate");
					this.OnBDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDate
		{
			get
			{
				return this._EDate;
			}
			set
			{
				if ((this._EDate != value))
				{
					this.OnEDateChanging(value);
					this.SendPropertyChanging();
					this._EDate = value;
					this.SendPropertyChanged("EDate");
					this.OnEDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="SmallInt")]
		public System.Nullable<short> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDisplay", DbType="Bit")]
		public System.Nullable<bool> IsDisplay
		{
			get
			{
				return this._IsDisplay;
			}
			set
			{
				if ((this._IsDisplay != value))
				{
					this.OnIsDisplayChanging(value);
					this.SendPropertyChanging();
					this._IsDisplay = value;
					this.SendPropertyChanged("IsDisplay");
					this.OnIsDisplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorePath", DbType="VarChar(MAX)")]
		public string StorePath
		{
			get
			{
				return this._StorePath;
			}
			set
			{
				if ((this._StorePath != value))
				{
					this.OnStorePathChanging(value);
					this.SendPropertyChanging();
					this._StorePath = value;
					this.SendPropertyChanged("StorePath");
					this.OnStorePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileLength", DbType="Int")]
		public System.Nullable<int> FileLength
		{
			get
			{
				return this._FileLength;
			}
			set
			{
				if ((this._FileLength != value))
				{
					this.OnFileLengthChanging(value);
					this.SendPropertyChanging();
					this._FileLength = value;
					this.SendPropertyChanged("FileLength");
					this.OnFileLengthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AdUser")]
	public partial class View_AdUser
	{
		
		private string _UserName;
		
		private string _MeterNo;
		
		private string _UserID;
		
		private string _CompanyID;
		
		private System.Nullable<long> _AP_ID;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private string _Street;
		
		private string _Community;
		
		private System.Nullable<long> _AC_ID;
		
		private string _Adress;
		
		private System.Nullable<System.DateTime> _AddTime;
		
		private string _Ver;
		
		private string _Context;
		
		public View_AdUser()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this._MeterNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_ID", DbType="BigInt")]
		public System.Nullable<long> AP_ID
		{
			get
			{
				return this._AP_ID;
			}
			set
			{
				if ((this._AP_ID != value))
				{
					this._AP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this._PublishDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="VarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Community", DbType="VarChar(50)")]
		public string Community
		{
			get
			{
				return this._Community;
			}
			set
			{
				if ((this._Community != value))
				{
					this._Community = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_ID", DbType="BigInt")]
		public System.Nullable<long> AC_ID
		{
			get
			{
				return this._AC_ID;
			}
			set
			{
				if ((this._AC_ID != value))
				{
					this._AC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="VarChar(100)")]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this._Adress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				if ((this._AddTime != value))
				{
					this._AddTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ver", DbType="Char(4)")]
		public string Ver
		{
			get
			{
				return this._Ver;
			}
			set
			{
				if ((this._Ver != value))
				{
					this._Ver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(200)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this._Context = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADUser")]
	public partial class ADUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _CompanyID;
		
		private System.Nullable<long> _AP_ID;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private string _Street;
		
		private string _Community;
		
		private System.Nullable<long> _AC_ID;
		
		private string _Adress;
		
		private System.Nullable<System.DateTime> _AddTime;
		
		private string _Ver;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnCompanyIDChanging(string value);
    partial void OnCompanyIDChanged();
    partial void OnAP_IDChanging(System.Nullable<long> value);
    partial void OnAP_IDChanged();
    partial void OnPublishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishDateChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnCommunityChanging(string value);
    partial void OnCommunityChanged();
    partial void OnAC_IDChanging(System.Nullable<long> value);
    partial void OnAC_IDChanged();
    partial void OnAdressChanging(string value);
    partial void OnAdressChanged();
    partial void OnAddTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnAddTimeChanged();
    partial void OnVerChanging(string value);
    partial void OnVerChanged();
    #endregion
		
		public ADUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_ID", DbType="BigInt")]
		public System.Nullable<long> AP_ID
		{
			get
			{
				return this._AP_ID;
			}
			set
			{
				if ((this._AP_ID != value))
				{
					this.OnAP_IDChanging(value);
					this.SendPropertyChanging();
					this._AP_ID = value;
					this.SendPropertyChanged("AP_ID");
					this.OnAP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this.OnPublishDateChanging(value);
					this.SendPropertyChanging();
					this._PublishDate = value;
					this.SendPropertyChanged("PublishDate");
					this.OnPublishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="VarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Community", DbType="VarChar(50)")]
		public string Community
		{
			get
			{
				return this._Community;
			}
			set
			{
				if ((this._Community != value))
				{
					this.OnCommunityChanging(value);
					this.SendPropertyChanging();
					this._Community = value;
					this.SendPropertyChanged("Community");
					this.OnCommunityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_ID", DbType="BigInt")]
		public System.Nullable<long> AC_ID
		{
			get
			{
				return this._AC_ID;
			}
			set
			{
				if ((this._AC_ID != value))
				{
					this.OnAC_IDChanging(value);
					this.SendPropertyChanging();
					this._AC_ID = value;
					this.SendPropertyChanged("AC_ID");
					this.OnAC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="VarChar(100)")]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this.OnAdressChanging(value);
					this.SendPropertyChanging();
					this._Adress = value;
					this.SendPropertyChanged("Adress");
					this.OnAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				if ((this._AddTime != value))
				{
					this.OnAddTimeChanging(value);
					this.SendPropertyChanging();
					this._AddTime = value;
					this.SendPropertyChanged("AddTime");
					this.OnAddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ver", DbType="Char(4)")]
		public string Ver
		{
			get
			{
				return this._Ver;
			}
			set
			{
				if ((this._Ver != value))
				{
					this.OnVerChanging(value);
					this.SendPropertyChanging();
					this._Ver = value;
					this.SendPropertyChanged("Ver");
					this.OnVerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_UserInfo")]
	public partial class View_UserInfo
	{
		
		private string _CompanyID;
		
		private string _UserID;
		
		private string _UserName;
		
		private string _Phone;
		
		private string _Street;
		
		private string _Community;
		
		private string _Door;
		
		private string _Address;
		
		private System.Nullable<char> _State;
		
		private string _CommunityName;
		
		private string _StreetName;
		
		private string _MeterNo;
		
		public View_UserInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="VarChar(50)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Community", DbType="VarChar(50)")]
		public string Community
		{
			get
			{
				return this._Community;
			}
			set
			{
				if ((this._Community != value))
				{
					this._Community = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Door", DbType="VarChar(50)")]
		public string Door
		{
			get
			{
				return this._Door;
			}
			set
			{
				if ((this._Door != value))
				{
					this._Door = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(1)")]
		public System.Nullable<char> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommunityName", DbType="VarChar(50)")]
		public string CommunityName
		{
			get
			{
				return this._CommunityName;
			}
			set
			{
				if ((this._CommunityName != value))
				{
					this._CommunityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(50)")]
		public string StreetName
		{
			get
			{
				return this._StreetName;
			}
			set
			{
				if ((this._StreetName != value))
				{
					this._StreetName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this._MeterNo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AdPublish")]
	public partial class View_AdPublish
	{
		
		private long _AP_ID;
		
		private string _CompanyID;
		
		private System.Nullable<long> _AC_ID;
		
		private string _AreaContext;
		
		private System.Nullable<System.DateTime> _PublishDate;
		
		private System.Nullable<int> _UserCount;
		
		private System.Nullable<short> _State;
		
		private string _Context;
		
		public View_AdPublish()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_ID", DbType="BigInt NOT NULL")]
		public long AP_ID
		{
			get
			{
				return this._AP_ID;
			}
			set
			{
				if ((this._AP_ID != value))
				{
					this._AP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_ID", DbType="BigInt")]
		public System.Nullable<long> AC_ID
		{
			get
			{
				return this._AC_ID;
			}
			set
			{
				if ((this._AC_ID != value))
				{
					this._AC_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaContext", DbType="VarChar(200)")]
		public string AreaContext
		{
			get
			{
				return this._AreaContext;
			}
			set
			{
				if ((this._AreaContext != value))
				{
					this._AreaContext = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishDate
		{
			get
			{
				return this._PublishDate;
			}
			set
			{
				if ((this._PublishDate != value))
				{
					this._PublishDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCount", DbType="Int")]
		public System.Nullable<int> UserCount
		{
			get
			{
				return this._UserCount;
			}
			set
			{
				if ((this._UserCount != value))
				{
					this._UserCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="SmallInt")]
		public System.Nullable<short> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(200)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this._Context = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AdPublishUserInfo")]
	public partial class View_AdPublishUserInfo
	{
		
		private long _ID;
		
		private long _AP_ID;
		
		private string _UserID;
		
		private string _CompanyID;
		
		private System.Nullable<short> _State;
		
		private System.Nullable<System.DateTime> _FinishedDate;
		
		private string _Context;
		
		private string _MeterNo;
		
		private string _UserName;
		
		private string _Adress;
		
		public View_AdPublishUserInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_ID", DbType="BigInt NOT NULL")]
		public long AP_ID
		{
			get
			{
				return this._AP_ID;
			}
			set
			{
				if ((this._AP_ID != value))
				{
					this._AP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Char(4)")]
		public string CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="SmallInt")]
		public System.Nullable<short> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinishedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FinishedDate
		{
			get
			{
				return this._FinishedDate;
			}
			set
			{
				if ((this._FinishedDate != value))
				{
					this._FinishedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="VarChar(MAX)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this._Context = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeterNo", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MeterNo
		{
			get
			{
				return this._MeterNo;
			}
			set
			{
				if ((this._MeterNo != value))
				{
					this._MeterNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="VarChar(100)")]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this._Adress = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
